include: ../flutter_analysis_options.yaml

linter:
  rules:
    unsafe_variance: false # Mostly inherited callbacks.
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
