version: 2
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Dart.
  - package-ecosystem: "pub"
    versioning-strategy: increase
    directories:
      - packages/**/*
      - tools
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Android (examples).
  - package-ecosystem: "gradle"
    directories:
      - "/packages/world_countries/example/android/"
      - "/packages/world_flags/example/android/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"
