version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Dart
  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/packages/sealed_countries/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/packages/world_countries/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/packages/sealed_languages/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/packages/sealed_currencies/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/tools/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Flutter (example)
  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/packages/world_countries/example/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Android (example)
  - package-ecosystem: "gradle"
    directory: "/packages/world_countries/example/android/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"
