version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Dart
  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "packages/countries_dart/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "packages/countries_flutter/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "packages/languages_dart/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "packages/currencies_dart/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"
