version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Dart
  - package-ecosystem: "pub"
    versioning-strategy: increase
    directories:
      - "/packages/tools/"
      - "/packages/_sealed_world_tests/"
      - "/packages/sealed_languages/"
      - "/packages/sealed_currencies/"
      - "/packages/sealed_countries/"
      - "/packages/world_flags/"
      - "/packages/world_flags/example/"
      - "/packages/world_countries/"
      - "/packages/world_countries/example/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Android (example)
  - package-ecosystem: "gradle"
    directories:
      - "/packages/world_countries/example/android/"
      - "/packages/world_flags/example/android/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"
