name: example
description: A flags package example application.
publish_to: none

version: 0.0.1+1

environment:
  sdk: ^3.4.1

dependencies:
  flags:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test: # From Google
    sdk: flutter
  lints: ^3.0.0 # From Google

flutter:
  uses-material-design: true
