name: widgetbook_world_flags
description: "A Widgetbook for the world_flags package."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.14.3
  world_flags:
    path: ../

dev_dependencies:
  widgetbook_cli: ^3.8.2

flutter:
  uses-material-design: true
