version: 0.0.1
name: flags
description: Country flags made with Flutter
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/flags
issue_tracker: https://github.com/tsinis/sealed_world/issues
publish_to: none # TODO!
topics:
  - flags
  - flag
  - country-flags
  - country-flag
  - coat-of-arms

screenshots: # TODO!
  - description: "Structure visualization"
    path: doc/structure.webp

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  sealed_countries: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.9 # From Google
  dart_code_metrics: # Flutter Favorite
    git:
      url: https://github.com/tsinis/dart-code-metrics
  flutter_test: # From Google
    sdk: flutter
  lints: ^3.0.0 # From Google
