// GENERATED CODE - DO NOT MODIFY BY HAND

part of "world_bloc.dart";

@Deprecated('Please use pattern matching with switch expressions instead.')
extension RegionalBlocFunctional on RegionalBloc {
  @Deprecated('Please use pattern matching with switch expressions instead.')
  R map<R>({
    required R Function(RegionalBloc blocAL) blocAL,
    required R Function(RegionalBloc blocASEAN) blocASEAN,
    required R Function(RegionalBloc blocAU) blocAU,
    required R Function(RegionalBloc blocCAIS) blocCAIS,
    required R Function(RegionalBloc blocCARICOM) blocCARICOM,
    required R Function(RegionalBloc blocCEFTA) blocCEFTA,
    required R Function(RegionalBloc blocEEU) blocEEU,
    required R Function(RegionalBloc blocEFTA) blocEFTA,
    required R Function(RegionalBloc blocEU) blocEU,
    required R Function(RegionalBloc blocNAFTA) blocNAFTA,
    required R Function(RegionalBloc blocPA) blocPA,
    required R Function(RegionalBloc blocSAARC) blocSAARC,
    required R Function(RegionalBloc blocUSAN) blocUSAN,
  }) => switch (this) {
    BlocAL() => blocAL(this),
    BlocASEAN() => blocASEAN(this),
    BlocAU() => blocAU(this),
    BlocCAIS() => blocCAIS(this),
    BlocCARICOM() => blocCARICOM(this),
    BlocCEFTA() => blocCEFTA(this),
    BlocEEU() => blocEEU(this),
    BlocEFTA() => blocEFTA(this),
    BlocEU() => blocEU(this),
    BlocNAFTA() => blocNAFTA(this),
    BlocPA() => blocPA(this),
    BlocSAARC() => blocSAARC(this),
    BlocUSAN() => blocUSAN(this),
    _ => throw ArgumentError("Unknown value: $this", name),
  };

  @Deprecated('Please use pattern matching with switch expressions instead.')
  R maybeMap<R>({
    required R Function(RegionalBloc regionalBloc) orElse,
    R Function(RegionalBloc blocAL)? blocAL,
    R Function(RegionalBloc blocASEAN)? blocASEAN,
    R Function(RegionalBloc blocAU)? blocAU,
    R Function(RegionalBloc blocCAIS)? blocCAIS,
    R Function(RegionalBloc blocCARICOM)? blocCARICOM,
    R Function(RegionalBloc blocCEFTA)? blocCEFTA,
    R Function(RegionalBloc blocEEU)? blocEEU,
    R Function(RegionalBloc blocEFTA)? blocEFTA,
    R Function(RegionalBloc blocEU)? blocEU,
    R Function(RegionalBloc blocNAFTA)? blocNAFTA,
    R Function(RegionalBloc blocPA)? blocPA,
    R Function(RegionalBloc blocSAARC)? blocSAARC,
    R Function(RegionalBloc blocUSAN)? blocUSAN,
  }) => switch (this) {
    BlocAL() => blocAL?.call(this) ?? orElse(this),
    BlocASEAN() => blocASEAN?.call(this) ?? orElse(this),
    BlocAU() => blocAU?.call(this) ?? orElse(this),
    BlocCAIS() => blocCAIS?.call(this) ?? orElse(this),
    BlocCARICOM() => blocCARICOM?.call(this) ?? orElse(this),
    BlocCEFTA() => blocCEFTA?.call(this) ?? orElse(this),
    BlocEEU() => blocEEU?.call(this) ?? orElse(this),
    BlocEFTA() => blocEFTA?.call(this) ?? orElse(this),
    BlocEU() => blocEU?.call(this) ?? orElse(this),
    BlocNAFTA() => blocNAFTA?.call(this) ?? orElse(this),
    BlocPA() => blocPA?.call(this) ?? orElse(this),
    BlocSAARC() => blocSAARC?.call(this) ?? orElse(this),
    BlocUSAN() => blocUSAN?.call(this) ?? orElse(this),
    _ => orElse(this),
  };

  @Deprecated('Please use pattern matching with switch expressions instead.')
  R maybeWhen<R>({
    required R Function() orElse,
    R Function()? blocAL,
    R Function()? blocASEAN,
    R Function()? blocAU,
    R Function()? blocCAIS,
    R Function()? blocCARICOM,
    R Function()? blocCEFTA,
    R Function()? blocEEU,
    R Function()? blocEFTA,
    R Function()? blocEU,
    R Function()? blocNAFTA,
    R Function()? blocPA,
    R Function()? blocSAARC,
    R Function()? blocUSAN,
  }) => switch (this) {
    BlocAL() => blocAL?.call() ?? orElse(),
    BlocASEAN() => blocASEAN?.call() ?? orElse(),
    BlocAU() => blocAU?.call() ?? orElse(),
    BlocCAIS() => blocCAIS?.call() ?? orElse(),
    BlocCARICOM() => blocCARICOM?.call() ?? orElse(),
    BlocCEFTA() => blocCEFTA?.call() ?? orElse(),
    BlocEEU() => blocEEU?.call() ?? orElse(),
    BlocEFTA() => blocEFTA?.call() ?? orElse(),
    BlocEU() => blocEU?.call() ?? orElse(),
    BlocNAFTA() => blocNAFTA?.call() ?? orElse(),
    BlocPA() => blocPA?.call() ?? orElse(),
    BlocSAARC() => blocSAARC?.call() ?? orElse(),
    BlocUSAN() => blocUSAN?.call() ?? orElse(),
    _ => orElse(),
  };

  @Deprecated('Please use pattern matching with switch expressions instead.')
  R when<R>({
    required R Function() blocAL,
    required R Function() blocASEAN,
    required R Function() blocAU,
    required R Function() blocCAIS,
    required R Function() blocCARICOM,
    required R Function() blocCEFTA,
    required R Function() blocEEU,
    required R Function() blocEFTA,
    required R Function() blocEU,
    required R Function() blocNAFTA,
    required R Function() blocPA,
    required R Function() blocSAARC,
    required R Function() blocUSAN,
  }) => switch (this) {
    BlocAL() => blocAL(),
    BlocASEAN() => blocASEAN(),
    BlocAU() => blocAU(),
    BlocCAIS() => blocCAIS(),
    BlocCARICOM() => blocCARICOM(),
    BlocCEFTA() => blocCEFTA(),
    BlocEEU() => blocEEU(),
    BlocEFTA() => blocEFTA(),
    BlocEU() => blocEU(),
    BlocNAFTA() => blocNAFTA(),
    BlocPA() => blocPA(),
    BlocSAARC() => blocSAARC(),
    BlocUSAN() => blocUSAN(),
    _ => throw ArgumentError("Unknown value: $this", name),
  };

  @Deprecated('Please use pattern matching with switch expressions instead.')
  R? maybeWhenOrNull<R>({
    R Function()? blocAL,
    R Function()? blocASEAN,
    R Function()? blocAU,
    R Function()? blocCAIS,
    R Function()? blocCARICOM,
    R Function()? blocCEFTA,
    R Function()? blocEEU,
    R Function()? blocEFTA,
    R Function()? blocEU,
    R Function()? blocNAFTA,
    R Function()? blocPA,
    R Function()? blocSAARC,
    R Function()? blocUSAN,
    R Function()? orElse,
  }) => switch (this) {
    BlocAL() => blocAL?.call() ?? orElse?.call(),
    BlocASEAN() => blocASEAN?.call() ?? orElse?.call(),
    BlocAU() => blocAU?.call() ?? orElse?.call(),
    BlocCAIS() => blocCAIS?.call() ?? orElse?.call(),
    BlocCARICOM() => blocCARICOM?.call() ?? orElse?.call(),
    BlocCEFTA() => blocCEFTA?.call() ?? orElse?.call(),
    BlocEEU() => blocEEU?.call() ?? orElse?.call(),
    BlocEFTA() => blocEFTA?.call() ?? orElse?.call(),
    BlocEU() => blocEU?.call() ?? orElse?.call(),
    BlocNAFTA() => blocNAFTA?.call() ?? orElse?.call(),
    BlocPA() => blocPA?.call() ?? orElse?.call(),
    BlocSAARC() => blocSAARC?.call() ?? orElse?.call(),
    BlocUSAN() => blocUSAN?.call() ?? orElse?.call(),
    _ => orElse?.call(),
  };
}
