import "package:sealed_countries/src/helpers/world_country/world_country_copy_with.dart";
import "package:sealed_countries/src/model/country/country.dart";
import "package:test/test.dart";

void main() => group("WorldCountryCopyWith", () {
  final element = WorldCountry.list.first;

  test("copyWith should return a new instance with updated code", () {
    final copy = element.copyWith(code: 123.toString());
    expect(copy.code, 123.toString());
    expect(element.code, isNot(copy.code));
    expect(element.postalCode, copy.postalCode);
    expect(element.capitalInfo, copy.capitalInfo);
    expect(element.fifa, copy.fifa);
    expect(element.gini, copy.gini);
    expect(element.demonyms, copy.demonyms);
    expect(element.bordersCodes, copy.bordersCodes);
    expect(element.subregion, copy.subregion);
    expect(element.idd, copy.idd);
    expect(element.currencies, copy.currencies);
    expect(element.cioc, copy.cioc);
    expect(element.startOfWeek, copy.startOfWeek);
    expect(element.hasCoatOfArms, copy.hasCoatOfArms);
    expect(element.landlocked, copy.landlocked);
    expect(element.unMember, copy.unMember);
    expect(element.independent, copy.independent);
    expect(element.timezones, copy.timezones);
    expect(element.car, copy.car);
    expect(element.population, copy.population);
    expect(element.areaMetric, copy.areaMetric);
    expect(element.maps, copy.maps);
    expect(element.emoji, copy.emoji);
    expect(element.latLng, copy.latLng);
    expect(element.languages, copy.languages);
    expect(element.continent, copy.continent);
    expect(element.altSpellings, copy.altSpellings);
    expect(element.codeNumeric, copy.codeNumeric);
    expect(element.codeShort, copy.codeShort);
    expect(element.namesNative, copy.namesNative);
    expect(element.tld, copy.tld);
  });

  test("copyWith should not return a new instance with updated code", () {
    final copy = element.copyWith();
    expect(element.code, copy.code);
    expect(element.postalCode, copy.postalCode);
    expect(element.capitalInfo, copy.capitalInfo);
    expect(element.fifa, copy.fifa);
    expect(element.gini, copy.gini);
    expect(element.demonyms, copy.demonyms);
    expect(element.bordersCodes, copy.bordersCodes);
    expect(element.subregion, copy.subregion);
    expect(element.idd, copy.idd);
    expect(element.currencies, copy.currencies);
    expect(element.cioc, copy.cioc);
    expect(element.startOfWeek, copy.startOfWeek);
    expect(element.hasCoatOfArms, copy.hasCoatOfArms);
    expect(element.landlocked, copy.landlocked);
    expect(element.unMember, copy.unMember);
    expect(element.independent, copy.independent);
    expect(element.timezones, copy.timezones);
    expect(element.car, copy.car);
    expect(element.population, copy.population);
    expect(element.areaMetric, copy.areaMetric);
    expect(element.maps, copy.maps);
    expect(element.emoji, copy.emoji);
    expect(element.latLng, copy.latLng);
    expect(element.languages, copy.languages);
    expect(element.continent, copy.continent);
    expect(element.altSpellings, copy.altSpellings);
    expect(element.codeNumeric, copy.codeNumeric);
    expect(element.codeShort, copy.codeShort);
    expect(element.namesNative, copy.namesNative);
    expect(element.tld, copy.tld);
  });
});
