include: ../../flutter_analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    diagnostic_describe_all_properties: false
    public_member_api_docs: false
