version: 3.5.0
name: world_flags_example
description: A world_flags package example application.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  world_flags:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  shaders:
    - shaders/cupertino_emoji_flag.frag
