name: countries_dart
description: Provides data for world countries in the form of sealed classes.
version: 0.0.1

publish_to: 'none' # TODO: Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0-128 <4.0.0'

dependencies:
  currencies_dart:
    path: ../currencies_dart
  languages_dart:
    path: ../languages_dart

dev_dependencies:
  # build_runner: ^2.4.0 # From Google
  dart_code_metrics: ^5.4.0 # Flutter Favorite
  lints: ^2.0.1 # From Google
  test: ^1.22.2 # From Google
