// GENERATED CODE - DO NOT MODIFY BY HAND

part of "../currency.dart";

extension FiatCurrencyFunctional on FiatCurrency {
  R map<R>({
    required R Function(FiatCurrency fiatAed) fiatAed,
    required R Function(FiatCurrency fiatAfn) fiatAfn,
    required R Function(FiatCurrency fiatAll) fiatAll,
    required R Function(FiatCurrency fiatAmd) fiatAmd,
    required R Function(FiatCurrency fiatAng) fiatAng,
    required R Function(FiatCurrency fiatAoa) fiatAoa,
    required R Function(FiatCurrency fiatArs) fiatArs,
    required R Function(FiatCurrency fiatAud) fiatAud,
    required R Function(FiatCurrency fiatAwg) fiatAwg,
    required R Function(FiatCurrency fiatAzn) fiatAzn,
    required R Function(FiatCurrency fiatBam) fiatBam,
    required R Function(FiatCurrency fiatBbd) fiatBbd,
    required R Function(FiatCurrency fiatBdt) fiatBdt,
    required R Function(FiatCurrency fiatBgn) fiatBgn,
    required R Function(FiatCurrency fiatBhd) fiatBhd,
    required R Function(FiatCurrency fiatBif) fiatBif,
    required R Function(FiatCurrency fiatBmd) fiatBmd,
    required R Function(FiatCurrency fiatBnd) fiatBnd,
    required R Function(FiatCurrency fiatBob) fiatBob,
    required R Function(FiatCurrency fiatBrl) fiatBrl,
    required R Function(FiatCurrency fiatBsd) fiatBsd,
    required R Function(FiatCurrency fiatBtn) fiatBtn,
    required R Function(FiatCurrency fiatBwp) fiatBwp,
    required R Function(FiatCurrency fiatByn) fiatByn,
    required R Function(FiatCurrency fiatBzd) fiatBzd,
    required R Function(FiatCurrency fiatCad) fiatCad,
    required R Function(FiatCurrency fiatCdf) fiatCdf,
    required R Function(FiatCurrency fiatChf) fiatChf,
    required R Function(FiatCurrency fiatClf) fiatClf,
    required R Function(FiatCurrency fiatClp) fiatClp,
    required R Function(FiatCurrency fiatCny) fiatCny,
    required R Function(FiatCurrency fiatCop) fiatCop,
    required R Function(FiatCurrency fiatCrc) fiatCrc,
    required R Function(FiatCurrency fiatCuc) fiatCuc,
    required R Function(FiatCurrency fiatCup) fiatCup,
    required R Function(FiatCurrency fiatCve) fiatCve,
    required R Function(FiatCurrency fiatCzk) fiatCzk,
    required R Function(FiatCurrency fiatDjf) fiatDjf,
    required R Function(FiatCurrency fiatDkk) fiatDkk,
    required R Function(FiatCurrency fiatDop) fiatDop,
    required R Function(FiatCurrency fiatDzd) fiatDzd,
    required R Function(FiatCurrency fiatEgp) fiatEgp,
    required R Function(FiatCurrency fiatErn) fiatErn,
    required R Function(FiatCurrency fiatEtb) fiatEtb,
    required R Function(FiatCurrency fiatEur) fiatEur,
    required R Function(FiatCurrency fiatFjd) fiatFjd,
    required R Function(FiatCurrency fiatFkp) fiatFkp,
    required R Function(FiatCurrency fiatGbp) fiatGbp,
    required R Function(FiatCurrency fiatGel) fiatGel,
    required R Function(FiatCurrency fiatGhs) fiatGhs,
    required R Function(FiatCurrency fiatGip) fiatGip,
    required R Function(FiatCurrency fiatGmd) fiatGmd,
    required R Function(FiatCurrency fiatGnf) fiatGnf,
    required R Function(FiatCurrency fiatGtq) fiatGtq,
    required R Function(FiatCurrency fiatGyd) fiatGyd,
    required R Function(FiatCurrency fiatHkd) fiatHkd,
    required R Function(FiatCurrency fiatHnl) fiatHnl,
    required R Function(FiatCurrency fiatHrk) fiatHrk,
    required R Function(FiatCurrency fiatHtg) fiatHtg,
    required R Function(FiatCurrency fiatHuf) fiatHuf,
    required R Function(FiatCurrency fiatIdr) fiatIdr,
    required R Function(FiatCurrency fiatIls) fiatIls,
    required R Function(FiatCurrency fiatInr) fiatInr,
    required R Function(FiatCurrency fiatIqd) fiatIqd,
    required R Function(FiatCurrency fiatIrr) fiatIrr,
    required R Function(FiatCurrency fiatIsk) fiatIsk,
    required R Function(FiatCurrency fiatJmd) fiatJmd,
    required R Function(FiatCurrency fiatJod) fiatJod,
    required R Function(FiatCurrency fiatJpy) fiatJpy,
    required R Function(FiatCurrency fiatKes) fiatKes,
    required R Function(FiatCurrency fiatKgs) fiatKgs,
    required R Function(FiatCurrency fiatKhr) fiatKhr,
    required R Function(FiatCurrency fiatKmf) fiatKmf,
    required R Function(FiatCurrency fiatKpw) fiatKpw,
    required R Function(FiatCurrency fiatKrw) fiatKrw,
    required R Function(FiatCurrency fiatKwd) fiatKwd,
    required R Function(FiatCurrency fiatKyd) fiatKyd,
    required R Function(FiatCurrency fiatKzt) fiatKzt,
    required R Function(FiatCurrency fiatLak) fiatLak,
    required R Function(FiatCurrency fiatLbp) fiatLbp,
    required R Function(FiatCurrency fiatLkr) fiatLkr,
    required R Function(FiatCurrency fiatLrd) fiatLrd,
    required R Function(FiatCurrency fiatLsl) fiatLsl,
    required R Function(FiatCurrency fiatLyd) fiatLyd,
    required R Function(FiatCurrency fiatMad) fiatMad,
    required R Function(FiatCurrency fiatMdl) fiatMdl,
    required R Function(FiatCurrency fiatMga) fiatMga,
    required R Function(FiatCurrency fiatMkd) fiatMkd,
    required R Function(FiatCurrency fiatMmk) fiatMmk,
    required R Function(FiatCurrency fiatMnt) fiatMnt,
    required R Function(FiatCurrency fiatMop) fiatMop,
    required R Function(FiatCurrency fiatMru) fiatMru,
    required R Function(FiatCurrency fiatMur) fiatMur,
    required R Function(FiatCurrency fiatMvr) fiatMvr,
    required R Function(FiatCurrency fiatMwk) fiatMwk,
    required R Function(FiatCurrency fiatMxn) fiatMxn,
    required R Function(FiatCurrency fiatMyr) fiatMyr,
    required R Function(FiatCurrency fiatMzn) fiatMzn,
    required R Function(FiatCurrency fiatNad) fiatNad,
    required R Function(FiatCurrency fiatNgn) fiatNgn,
    required R Function(FiatCurrency fiatNio) fiatNio,
    required R Function(FiatCurrency fiatNok) fiatNok,
    required R Function(FiatCurrency fiatNpr) fiatNpr,
    required R Function(FiatCurrency fiatNzd) fiatNzd,
    required R Function(FiatCurrency fiatOmr) fiatOmr,
    required R Function(FiatCurrency fiatPab) fiatPab,
    required R Function(FiatCurrency fiatPen) fiatPen,
    required R Function(FiatCurrency fiatPgk) fiatPgk,
    required R Function(FiatCurrency fiatPhp) fiatPhp,
    required R Function(FiatCurrency fiatPkr) fiatPkr,
    required R Function(FiatCurrency fiatPln) fiatPln,
    required R Function(FiatCurrency fiatPyg) fiatPyg,
    required R Function(FiatCurrency fiatQar) fiatQar,
    required R Function(FiatCurrency fiatRon) fiatRon,
    required R Function(FiatCurrency fiatRsd) fiatRsd,
    required R Function(FiatCurrency fiatRub) fiatRub,
    required R Function(FiatCurrency fiatRwf) fiatRwf,
    required R Function(FiatCurrency fiatSar) fiatSar,
    required R Function(FiatCurrency fiatSbd) fiatSbd,
    required R Function(FiatCurrency fiatScr) fiatScr,
    required R Function(FiatCurrency fiatSdg) fiatSdg,
    required R Function(FiatCurrency fiatSek) fiatSek,
    required R Function(FiatCurrency fiatSgd) fiatSgd,
    required R Function(FiatCurrency fiatShp) fiatShp,
    required R Function(FiatCurrency fiatSle) fiatSle,
    required R Function(FiatCurrency fiatSll) fiatSll,
    required R Function(FiatCurrency fiatSos) fiatSos,
    required R Function(FiatCurrency fiatSrd) fiatSrd,
    required R Function(FiatCurrency fiatSsp) fiatSsp,
    required R Function(FiatCurrency fiatStn) fiatStn,
    required R Function(FiatCurrency fiatSvc) fiatSvc,
    required R Function(FiatCurrency fiatSyp) fiatSyp,
    required R Function(FiatCurrency fiatSzl) fiatSzl,
    required R Function(FiatCurrency fiatThb) fiatThb,
    required R Function(FiatCurrency fiatTjs) fiatTjs,
    required R Function(FiatCurrency fiatTmt) fiatTmt,
    required R Function(FiatCurrency fiatTnd) fiatTnd,
    required R Function(FiatCurrency fiatTop) fiatTop,
    required R Function(FiatCurrency fiatTry) fiatTry,
    required R Function(FiatCurrency fiatTtd) fiatTtd,
    required R Function(FiatCurrency fiatTwd) fiatTwd,
    required R Function(FiatCurrency fiatTzs) fiatTzs,
    required R Function(FiatCurrency fiatUah) fiatUah,
    required R Function(FiatCurrency fiatUgx) fiatUgx,
    required R Function(FiatCurrency fiatUsd) fiatUsd,
    required R Function(FiatCurrency fiatUyu) fiatUyu,
    required R Function(FiatCurrency fiatUzs) fiatUzs,
    required R Function(FiatCurrency fiatVes) fiatVes,
    required R Function(FiatCurrency fiatVnd) fiatVnd,
    required R Function(FiatCurrency fiatVuv) fiatVuv,
    required R Function(FiatCurrency fiatWst) fiatWst,
    required R Function(FiatCurrency fiatXaf) fiatXaf,
    required R Function(FiatCurrency fiatXag) fiatXag,
    required R Function(FiatCurrency fiatXau) fiatXau,
    required R Function(FiatCurrency fiatXba) fiatXba,
    required R Function(FiatCurrency fiatXbb) fiatXbb,
    required R Function(FiatCurrency fiatXbc) fiatXbc,
    required R Function(FiatCurrency fiatXbd) fiatXbd,
    required R Function(FiatCurrency fiatXcd) fiatXcd,
    required R Function(FiatCurrency fiatXdr) fiatXdr,
    required R Function(FiatCurrency fiatXof) fiatXof,
    required R Function(FiatCurrency fiatXpd) fiatXpd,
    required R Function(FiatCurrency fiatXpf) fiatXpf,
    required R Function(FiatCurrency fiatXpt) fiatXpt,
    required R Function(FiatCurrency fiatXts) fiatXts,
    required R Function(FiatCurrency fiatYer) fiatYer,
    required R Function(FiatCurrency fiatZar) fiatZar,
    required R Function(FiatCurrency fiatZwl) fiatZwl,
    required R Function(FiatCurrency fiatZmw) fiatZmw,
  }) =>
      switch (this) {
        FiatAed() => fiatAed(this),
        FiatAfn() => fiatAfn(this),
        FiatAll() => fiatAll(this),
        FiatAmd() => fiatAmd(this),
        FiatAng() => fiatAng(this),
        FiatAoa() => fiatAoa(this),
        FiatArs() => fiatArs(this),
        FiatAud() => fiatAud(this),
        FiatAwg() => fiatAwg(this),
        FiatAzn() => fiatAzn(this),
        FiatBam() => fiatBam(this),
        FiatBbd() => fiatBbd(this),
        FiatBdt() => fiatBdt(this),
        FiatBgn() => fiatBgn(this),
        FiatBhd() => fiatBhd(this),
        FiatBif() => fiatBif(this),
        FiatBmd() => fiatBmd(this),
        FiatBnd() => fiatBnd(this),
        FiatBob() => fiatBob(this),
        FiatBrl() => fiatBrl(this),
        FiatBsd() => fiatBsd(this),
        FiatBtn() => fiatBtn(this),
        FiatBwp() => fiatBwp(this),
        FiatByn() => fiatByn(this),
        FiatBzd() => fiatBzd(this),
        FiatCad() => fiatCad(this),
        FiatCdf() => fiatCdf(this),
        FiatChf() => fiatChf(this),
        FiatClf() => fiatClf(this),
        FiatClp() => fiatClp(this),
        FiatCny() => fiatCny(this),
        FiatCop() => fiatCop(this),
        FiatCrc() => fiatCrc(this),
        FiatCuc() => fiatCuc(this),
        FiatCup() => fiatCup(this),
        FiatCve() => fiatCve(this),
        FiatCzk() => fiatCzk(this),
        FiatDjf() => fiatDjf(this),
        FiatDkk() => fiatDkk(this),
        FiatDop() => fiatDop(this),
        FiatDzd() => fiatDzd(this),
        FiatEgp() => fiatEgp(this),
        FiatErn() => fiatErn(this),
        FiatEtb() => fiatEtb(this),
        FiatEur() => fiatEur(this),
        FiatFjd() => fiatFjd(this),
        FiatFkp() => fiatFkp(this),
        FiatGbp() => fiatGbp(this),
        FiatGel() => fiatGel(this),
        FiatGhs() => fiatGhs(this),
        FiatGip() => fiatGip(this),
        FiatGmd() => fiatGmd(this),
        FiatGnf() => fiatGnf(this),
        FiatGtq() => fiatGtq(this),
        FiatGyd() => fiatGyd(this),
        FiatHkd() => fiatHkd(this),
        FiatHnl() => fiatHnl(this),
        FiatHrk() => fiatHrk(this),
        FiatHtg() => fiatHtg(this),
        FiatHuf() => fiatHuf(this),
        FiatIdr() => fiatIdr(this),
        FiatIls() => fiatIls(this),
        FiatInr() => fiatInr(this),
        FiatIqd() => fiatIqd(this),
        FiatIrr() => fiatIrr(this),
        FiatIsk() => fiatIsk(this),
        FiatJmd() => fiatJmd(this),
        FiatJod() => fiatJod(this),
        FiatJpy() => fiatJpy(this),
        FiatKes() => fiatKes(this),
        FiatKgs() => fiatKgs(this),
        FiatKhr() => fiatKhr(this),
        FiatKmf() => fiatKmf(this),
        FiatKpw() => fiatKpw(this),
        FiatKrw() => fiatKrw(this),
        FiatKwd() => fiatKwd(this),
        FiatKyd() => fiatKyd(this),
        FiatKzt() => fiatKzt(this),
        FiatLak() => fiatLak(this),
        FiatLbp() => fiatLbp(this),
        FiatLkr() => fiatLkr(this),
        FiatLrd() => fiatLrd(this),
        FiatLsl() => fiatLsl(this),
        FiatLyd() => fiatLyd(this),
        FiatMad() => fiatMad(this),
        FiatMdl() => fiatMdl(this),
        FiatMga() => fiatMga(this),
        FiatMkd() => fiatMkd(this),
        FiatMmk() => fiatMmk(this),
        FiatMnt() => fiatMnt(this),
        FiatMop() => fiatMop(this),
        FiatMru() => fiatMru(this),
        FiatMur() => fiatMur(this),
        FiatMvr() => fiatMvr(this),
        FiatMwk() => fiatMwk(this),
        FiatMxn() => fiatMxn(this),
        FiatMyr() => fiatMyr(this),
        FiatMzn() => fiatMzn(this),
        FiatNad() => fiatNad(this),
        FiatNgn() => fiatNgn(this),
        FiatNio() => fiatNio(this),
        FiatNok() => fiatNok(this),
        FiatNpr() => fiatNpr(this),
        FiatNzd() => fiatNzd(this),
        FiatOmr() => fiatOmr(this),
        FiatPab() => fiatPab(this),
        FiatPen() => fiatPen(this),
        FiatPgk() => fiatPgk(this),
        FiatPhp() => fiatPhp(this),
        FiatPkr() => fiatPkr(this),
        FiatPln() => fiatPln(this),
        FiatPyg() => fiatPyg(this),
        FiatQar() => fiatQar(this),
        FiatRon() => fiatRon(this),
        FiatRsd() => fiatRsd(this),
        FiatRub() => fiatRub(this),
        FiatRwf() => fiatRwf(this),
        FiatSar() => fiatSar(this),
        FiatSbd() => fiatSbd(this),
        FiatScr() => fiatScr(this),
        FiatSdg() => fiatSdg(this),
        FiatSek() => fiatSek(this),
        FiatSgd() => fiatSgd(this),
        FiatShp() => fiatShp(this),
        FiatSle() => fiatSle(this),
        FiatSll() => fiatSll(this),
        FiatSos() => fiatSos(this),
        FiatSrd() => fiatSrd(this),
        FiatSsp() => fiatSsp(this),
        FiatStn() => fiatStn(this),
        FiatSvc() => fiatSvc(this),
        FiatSyp() => fiatSyp(this),
        FiatSzl() => fiatSzl(this),
        FiatThb() => fiatThb(this),
        FiatTjs() => fiatTjs(this),
        FiatTmt() => fiatTmt(this),
        FiatTnd() => fiatTnd(this),
        FiatTop() => fiatTop(this),
        FiatTry() => fiatTry(this),
        FiatTtd() => fiatTtd(this),
        FiatTwd() => fiatTwd(this),
        FiatTzs() => fiatTzs(this),
        FiatUah() => fiatUah(this),
        FiatUgx() => fiatUgx(this),
        FiatUsd() => fiatUsd(this),
        FiatUyu() => fiatUyu(this),
        FiatUzs() => fiatUzs(this),
        FiatVes() => fiatVes(this),
        FiatVnd() => fiatVnd(this),
        FiatVuv() => fiatVuv(this),
        FiatWst() => fiatWst(this),
        FiatXaf() => fiatXaf(this),
        FiatXag() => fiatXag(this),
        FiatXau() => fiatXau(this),
        FiatXba() => fiatXba(this),
        FiatXbb() => fiatXbb(this),
        FiatXbc() => fiatXbc(this),
        FiatXbd() => fiatXbd(this),
        FiatXcd() => fiatXcd(this),
        FiatXdr() => fiatXdr(this),
        FiatXof() => fiatXof(this),
        FiatXpd() => fiatXpd(this),
        FiatXpf() => fiatXpf(this),
        FiatXpt() => fiatXpt(this),
        FiatXts() => fiatXts(this),
        FiatYer() => fiatYer(this),
        FiatZar() => fiatZar(this),
        FiatZwl() => fiatZwl(this),
        FiatZmw() => fiatZmw(this),
        _ => throw ArgumentError("Unknown value: $this", name),
      };

  R maybeMap<R>({
    required R Function(FiatCurrency currency) orElse,
    R Function(FiatCurrency fiatAed)? fiatAed,
    R Function(FiatCurrency fiatAfn)? fiatAfn,
    R Function(FiatCurrency fiatAll)? fiatAll,
    R Function(FiatCurrency fiatAmd)? fiatAmd,
    R Function(FiatCurrency fiatAng)? fiatAng,
    R Function(FiatCurrency fiatAoa)? fiatAoa,
    R Function(FiatCurrency fiatArs)? fiatArs,
    R Function(FiatCurrency fiatAud)? fiatAud,
    R Function(FiatCurrency fiatAwg)? fiatAwg,
    R Function(FiatCurrency fiatAzn)? fiatAzn,
    R Function(FiatCurrency fiatBam)? fiatBam,
    R Function(FiatCurrency fiatBbd)? fiatBbd,
    R Function(FiatCurrency fiatBdt)? fiatBdt,
    R Function(FiatCurrency fiatBgn)? fiatBgn,
    R Function(FiatCurrency fiatBhd)? fiatBhd,
    R Function(FiatCurrency fiatBif)? fiatBif,
    R Function(FiatCurrency fiatBmd)? fiatBmd,
    R Function(FiatCurrency fiatBnd)? fiatBnd,
    R Function(FiatCurrency fiatBob)? fiatBob,
    R Function(FiatCurrency fiatBrl)? fiatBrl,
    R Function(FiatCurrency fiatBsd)? fiatBsd,
    R Function(FiatCurrency fiatBtn)? fiatBtn,
    R Function(FiatCurrency fiatBwp)? fiatBwp,
    R Function(FiatCurrency fiatByn)? fiatByn,
    R Function(FiatCurrency fiatBzd)? fiatBzd,
    R Function(FiatCurrency fiatCad)? fiatCad,
    R Function(FiatCurrency fiatCdf)? fiatCdf,
    R Function(FiatCurrency fiatChf)? fiatChf,
    R Function(FiatCurrency fiatClf)? fiatClf,
    R Function(FiatCurrency fiatClp)? fiatClp,
    R Function(FiatCurrency fiatCny)? fiatCny,
    R Function(FiatCurrency fiatCop)? fiatCop,
    R Function(FiatCurrency fiatCrc)? fiatCrc,
    R Function(FiatCurrency fiatCuc)? fiatCuc,
    R Function(FiatCurrency fiatCup)? fiatCup,
    R Function(FiatCurrency fiatCve)? fiatCve,
    R Function(FiatCurrency fiatCzk)? fiatCzk,
    R Function(FiatCurrency fiatDjf)? fiatDjf,
    R Function(FiatCurrency fiatDkk)? fiatDkk,
    R Function(FiatCurrency fiatDop)? fiatDop,
    R Function(FiatCurrency fiatDzd)? fiatDzd,
    R Function(FiatCurrency fiatEgp)? fiatEgp,
    R Function(FiatCurrency fiatErn)? fiatErn,
    R Function(FiatCurrency fiatEtb)? fiatEtb,
    R Function(FiatCurrency fiatEur)? fiatEur,
    R Function(FiatCurrency fiatFjd)? fiatFjd,
    R Function(FiatCurrency fiatFkp)? fiatFkp,
    R Function(FiatCurrency fiatGbp)? fiatGbp,
    R Function(FiatCurrency fiatGel)? fiatGel,
    R Function(FiatCurrency fiatGhs)? fiatGhs,
    R Function(FiatCurrency fiatGip)? fiatGip,
    R Function(FiatCurrency fiatGmd)? fiatGmd,
    R Function(FiatCurrency fiatGnf)? fiatGnf,
    R Function(FiatCurrency fiatGtq)? fiatGtq,
    R Function(FiatCurrency fiatGyd)? fiatGyd,
    R Function(FiatCurrency fiatHkd)? fiatHkd,
    R Function(FiatCurrency fiatHnl)? fiatHnl,
    R Function(FiatCurrency fiatHrk)? fiatHrk,
    R Function(FiatCurrency fiatHtg)? fiatHtg,
    R Function(FiatCurrency fiatHuf)? fiatHuf,
    R Function(FiatCurrency fiatIdr)? fiatIdr,
    R Function(FiatCurrency fiatIls)? fiatIls,
    R Function(FiatCurrency fiatInr)? fiatInr,
    R Function(FiatCurrency fiatIqd)? fiatIqd,
    R Function(FiatCurrency fiatIrr)? fiatIrr,
    R Function(FiatCurrency fiatIsk)? fiatIsk,
    R Function(FiatCurrency fiatJmd)? fiatJmd,
    R Function(FiatCurrency fiatJod)? fiatJod,
    R Function(FiatCurrency fiatJpy)? fiatJpy,
    R Function(FiatCurrency fiatKes)? fiatKes,
    R Function(FiatCurrency fiatKgs)? fiatKgs,
    R Function(FiatCurrency fiatKhr)? fiatKhr,
    R Function(FiatCurrency fiatKmf)? fiatKmf,
    R Function(FiatCurrency fiatKpw)? fiatKpw,
    R Function(FiatCurrency fiatKrw)? fiatKrw,
    R Function(FiatCurrency fiatKwd)? fiatKwd,
    R Function(FiatCurrency fiatKyd)? fiatKyd,
    R Function(FiatCurrency fiatKzt)? fiatKzt,
    R Function(FiatCurrency fiatLak)? fiatLak,
    R Function(FiatCurrency fiatLbp)? fiatLbp,
    R Function(FiatCurrency fiatLkr)? fiatLkr,
    R Function(FiatCurrency fiatLrd)? fiatLrd,
    R Function(FiatCurrency fiatLsl)? fiatLsl,
    R Function(FiatCurrency fiatLyd)? fiatLyd,
    R Function(FiatCurrency fiatMad)? fiatMad,
    R Function(FiatCurrency fiatMdl)? fiatMdl,
    R Function(FiatCurrency fiatMga)? fiatMga,
    R Function(FiatCurrency fiatMkd)? fiatMkd,
    R Function(FiatCurrency fiatMmk)? fiatMmk,
    R Function(FiatCurrency fiatMnt)? fiatMnt,
    R Function(FiatCurrency fiatMop)? fiatMop,
    R Function(FiatCurrency fiatMru)? fiatMru,
    R Function(FiatCurrency fiatMur)? fiatMur,
    R Function(FiatCurrency fiatMvr)? fiatMvr,
    R Function(FiatCurrency fiatMwk)? fiatMwk,
    R Function(FiatCurrency fiatMxn)? fiatMxn,
    R Function(FiatCurrency fiatMyr)? fiatMyr,
    R Function(FiatCurrency fiatMzn)? fiatMzn,
    R Function(FiatCurrency fiatNad)? fiatNad,
    R Function(FiatCurrency fiatNgn)? fiatNgn,
    R Function(FiatCurrency fiatNio)? fiatNio,
    R Function(FiatCurrency fiatNok)? fiatNok,
    R Function(FiatCurrency fiatNpr)? fiatNpr,
    R Function(FiatCurrency fiatNzd)? fiatNzd,
    R Function(FiatCurrency fiatOmr)? fiatOmr,
    R Function(FiatCurrency fiatPab)? fiatPab,
    R Function(FiatCurrency fiatPen)? fiatPen,
    R Function(FiatCurrency fiatPgk)? fiatPgk,
    R Function(FiatCurrency fiatPhp)? fiatPhp,
    R Function(FiatCurrency fiatPkr)? fiatPkr,
    R Function(FiatCurrency fiatPln)? fiatPln,
    R Function(FiatCurrency fiatPyg)? fiatPyg,
    R Function(FiatCurrency fiatQar)? fiatQar,
    R Function(FiatCurrency fiatRon)? fiatRon,
    R Function(FiatCurrency fiatRsd)? fiatRsd,
    R Function(FiatCurrency fiatRub)? fiatRub,
    R Function(FiatCurrency fiatRwf)? fiatRwf,
    R Function(FiatCurrency fiatSar)? fiatSar,
    R Function(FiatCurrency fiatSbd)? fiatSbd,
    R Function(FiatCurrency fiatScr)? fiatScr,
    R Function(FiatCurrency fiatSdg)? fiatSdg,
    R Function(FiatCurrency fiatSek)? fiatSek,
    R Function(FiatCurrency fiatSgd)? fiatSgd,
    R Function(FiatCurrency fiatShp)? fiatShp,
    R Function(FiatCurrency fiatSle)? fiatSle,
    R Function(FiatCurrency fiatSll)? fiatSll,
    R Function(FiatCurrency fiatSos)? fiatSos,
    R Function(FiatCurrency fiatSrd)? fiatSrd,
    R Function(FiatCurrency fiatSsp)? fiatSsp,
    R Function(FiatCurrency fiatStn)? fiatStn,
    R Function(FiatCurrency fiatSvc)? fiatSvc,
    R Function(FiatCurrency fiatSyp)? fiatSyp,
    R Function(FiatCurrency fiatSzl)? fiatSzl,
    R Function(FiatCurrency fiatThb)? fiatThb,
    R Function(FiatCurrency fiatTjs)? fiatTjs,
    R Function(FiatCurrency fiatTmt)? fiatTmt,
    R Function(FiatCurrency fiatTnd)? fiatTnd,
    R Function(FiatCurrency fiatTop)? fiatTop,
    R Function(FiatCurrency fiatTry)? fiatTry,
    R Function(FiatCurrency fiatTtd)? fiatTtd,
    R Function(FiatCurrency fiatTwd)? fiatTwd,
    R Function(FiatCurrency fiatTzs)? fiatTzs,
    R Function(FiatCurrency fiatUah)? fiatUah,
    R Function(FiatCurrency fiatUgx)? fiatUgx,
    R Function(FiatCurrency fiatUsd)? fiatUsd,
    R Function(FiatCurrency fiatUyu)? fiatUyu,
    R Function(FiatCurrency fiatUzs)? fiatUzs,
    R Function(FiatCurrency fiatVes)? fiatVes,
    R Function(FiatCurrency fiatVnd)? fiatVnd,
    R Function(FiatCurrency fiatVuv)? fiatVuv,
    R Function(FiatCurrency fiatWst)? fiatWst,
    R Function(FiatCurrency fiatXaf)? fiatXaf,
    R Function(FiatCurrency fiatXag)? fiatXag,
    R Function(FiatCurrency fiatXau)? fiatXau,
    R Function(FiatCurrency fiatXba)? fiatXba,
    R Function(FiatCurrency fiatXbb)? fiatXbb,
    R Function(FiatCurrency fiatXbc)? fiatXbc,
    R Function(FiatCurrency fiatXbd)? fiatXbd,
    R Function(FiatCurrency fiatXcd)? fiatXcd,
    R Function(FiatCurrency fiatXdr)? fiatXdr,
    R Function(FiatCurrency fiatXof)? fiatXof,
    R Function(FiatCurrency fiatXpd)? fiatXpd,
    R Function(FiatCurrency fiatXpf)? fiatXpf,
    R Function(FiatCurrency fiatXpt)? fiatXpt,
    R Function(FiatCurrency fiatXts)? fiatXts,
    R Function(FiatCurrency fiatYer)? fiatYer,
    R Function(FiatCurrency fiatZar)? fiatZar,
    R Function(FiatCurrency fiatZwl)? fiatZwl,
    R Function(FiatCurrency fiatZmw)? fiatZmw,
  }) =>
      switch (this) {
        FiatAed() => fiatAed?.call(this) ?? orElse(this),
        FiatAfn() => fiatAfn?.call(this) ?? orElse(this),
        FiatAll() => fiatAll?.call(this) ?? orElse(this),
        FiatAmd() => fiatAmd?.call(this) ?? orElse(this),
        FiatAng() => fiatAng?.call(this) ?? orElse(this),
        FiatAoa() => fiatAoa?.call(this) ?? orElse(this),
        FiatArs() => fiatArs?.call(this) ?? orElse(this),
        FiatAud() => fiatAud?.call(this) ?? orElse(this),
        FiatAwg() => fiatAwg?.call(this) ?? orElse(this),
        FiatAzn() => fiatAzn?.call(this) ?? orElse(this),
        FiatBam() => fiatBam?.call(this) ?? orElse(this),
        FiatBbd() => fiatBbd?.call(this) ?? orElse(this),
        FiatBdt() => fiatBdt?.call(this) ?? orElse(this),
        FiatBgn() => fiatBgn?.call(this) ?? orElse(this),
        FiatBhd() => fiatBhd?.call(this) ?? orElse(this),
        FiatBif() => fiatBif?.call(this) ?? orElse(this),
        FiatBmd() => fiatBmd?.call(this) ?? orElse(this),
        FiatBnd() => fiatBnd?.call(this) ?? orElse(this),
        FiatBob() => fiatBob?.call(this) ?? orElse(this),
        FiatBrl() => fiatBrl?.call(this) ?? orElse(this),
        FiatBsd() => fiatBsd?.call(this) ?? orElse(this),
        FiatBtn() => fiatBtn?.call(this) ?? orElse(this),
        FiatBwp() => fiatBwp?.call(this) ?? orElse(this),
        FiatByn() => fiatByn?.call(this) ?? orElse(this),
        FiatBzd() => fiatBzd?.call(this) ?? orElse(this),
        FiatCad() => fiatCad?.call(this) ?? orElse(this),
        FiatCdf() => fiatCdf?.call(this) ?? orElse(this),
        FiatChf() => fiatChf?.call(this) ?? orElse(this),
        FiatClf() => fiatClf?.call(this) ?? orElse(this),
        FiatClp() => fiatClp?.call(this) ?? orElse(this),
        FiatCny() => fiatCny?.call(this) ?? orElse(this),
        FiatCop() => fiatCop?.call(this) ?? orElse(this),
        FiatCrc() => fiatCrc?.call(this) ?? orElse(this),
        FiatCuc() => fiatCuc?.call(this) ?? orElse(this),
        FiatCup() => fiatCup?.call(this) ?? orElse(this),
        FiatCve() => fiatCve?.call(this) ?? orElse(this),
        FiatCzk() => fiatCzk?.call(this) ?? orElse(this),
        FiatDjf() => fiatDjf?.call(this) ?? orElse(this),
        FiatDkk() => fiatDkk?.call(this) ?? orElse(this),
        FiatDop() => fiatDop?.call(this) ?? orElse(this),
        FiatDzd() => fiatDzd?.call(this) ?? orElse(this),
        FiatEgp() => fiatEgp?.call(this) ?? orElse(this),
        FiatErn() => fiatErn?.call(this) ?? orElse(this),
        FiatEtb() => fiatEtb?.call(this) ?? orElse(this),
        FiatEur() => fiatEur?.call(this) ?? orElse(this),
        FiatFjd() => fiatFjd?.call(this) ?? orElse(this),
        FiatFkp() => fiatFkp?.call(this) ?? orElse(this),
        FiatGbp() => fiatGbp?.call(this) ?? orElse(this),
        FiatGel() => fiatGel?.call(this) ?? orElse(this),
        FiatGhs() => fiatGhs?.call(this) ?? orElse(this),
        FiatGip() => fiatGip?.call(this) ?? orElse(this),
        FiatGmd() => fiatGmd?.call(this) ?? orElse(this),
        FiatGnf() => fiatGnf?.call(this) ?? orElse(this),
        FiatGtq() => fiatGtq?.call(this) ?? orElse(this),
        FiatGyd() => fiatGyd?.call(this) ?? orElse(this),
        FiatHkd() => fiatHkd?.call(this) ?? orElse(this),
        FiatHnl() => fiatHnl?.call(this) ?? orElse(this),
        FiatHrk() => fiatHrk?.call(this) ?? orElse(this),
        FiatHtg() => fiatHtg?.call(this) ?? orElse(this),
        FiatHuf() => fiatHuf?.call(this) ?? orElse(this),
        FiatIdr() => fiatIdr?.call(this) ?? orElse(this),
        FiatIls() => fiatIls?.call(this) ?? orElse(this),
        FiatInr() => fiatInr?.call(this) ?? orElse(this),
        FiatIqd() => fiatIqd?.call(this) ?? orElse(this),
        FiatIrr() => fiatIrr?.call(this) ?? orElse(this),
        FiatIsk() => fiatIsk?.call(this) ?? orElse(this),
        FiatJmd() => fiatJmd?.call(this) ?? orElse(this),
        FiatJod() => fiatJod?.call(this) ?? orElse(this),
        FiatJpy() => fiatJpy?.call(this) ?? orElse(this),
        FiatKes() => fiatKes?.call(this) ?? orElse(this),
        FiatKgs() => fiatKgs?.call(this) ?? orElse(this),
        FiatKhr() => fiatKhr?.call(this) ?? orElse(this),
        FiatKmf() => fiatKmf?.call(this) ?? orElse(this),
        FiatKpw() => fiatKpw?.call(this) ?? orElse(this),
        FiatKrw() => fiatKrw?.call(this) ?? orElse(this),
        FiatKwd() => fiatKwd?.call(this) ?? orElse(this),
        FiatKyd() => fiatKyd?.call(this) ?? orElse(this),
        FiatKzt() => fiatKzt?.call(this) ?? orElse(this),
        FiatLak() => fiatLak?.call(this) ?? orElse(this),
        FiatLbp() => fiatLbp?.call(this) ?? orElse(this),
        FiatLkr() => fiatLkr?.call(this) ?? orElse(this),
        FiatLrd() => fiatLrd?.call(this) ?? orElse(this),
        FiatLsl() => fiatLsl?.call(this) ?? orElse(this),
        FiatLyd() => fiatLyd?.call(this) ?? orElse(this),
        FiatMad() => fiatMad?.call(this) ?? orElse(this),
        FiatMdl() => fiatMdl?.call(this) ?? orElse(this),
        FiatMga() => fiatMga?.call(this) ?? orElse(this),
        FiatMkd() => fiatMkd?.call(this) ?? orElse(this),
        FiatMmk() => fiatMmk?.call(this) ?? orElse(this),
        FiatMnt() => fiatMnt?.call(this) ?? orElse(this),
        FiatMop() => fiatMop?.call(this) ?? orElse(this),
        FiatMru() => fiatMru?.call(this) ?? orElse(this),
        FiatMur() => fiatMur?.call(this) ?? orElse(this),
        FiatMvr() => fiatMvr?.call(this) ?? orElse(this),
        FiatMwk() => fiatMwk?.call(this) ?? orElse(this),
        FiatMxn() => fiatMxn?.call(this) ?? orElse(this),
        FiatMyr() => fiatMyr?.call(this) ?? orElse(this),
        FiatMzn() => fiatMzn?.call(this) ?? orElse(this),
        FiatNad() => fiatNad?.call(this) ?? orElse(this),
        FiatNgn() => fiatNgn?.call(this) ?? orElse(this),
        FiatNio() => fiatNio?.call(this) ?? orElse(this),
        FiatNok() => fiatNok?.call(this) ?? orElse(this),
        FiatNpr() => fiatNpr?.call(this) ?? orElse(this),
        FiatNzd() => fiatNzd?.call(this) ?? orElse(this),
        FiatOmr() => fiatOmr?.call(this) ?? orElse(this),
        FiatPab() => fiatPab?.call(this) ?? orElse(this),
        FiatPen() => fiatPen?.call(this) ?? orElse(this),
        FiatPgk() => fiatPgk?.call(this) ?? orElse(this),
        FiatPhp() => fiatPhp?.call(this) ?? orElse(this),
        FiatPkr() => fiatPkr?.call(this) ?? orElse(this),
        FiatPln() => fiatPln?.call(this) ?? orElse(this),
        FiatPyg() => fiatPyg?.call(this) ?? orElse(this),
        FiatQar() => fiatQar?.call(this) ?? orElse(this),
        FiatRon() => fiatRon?.call(this) ?? orElse(this),
        FiatRsd() => fiatRsd?.call(this) ?? orElse(this),
        FiatRub() => fiatRub?.call(this) ?? orElse(this),
        FiatRwf() => fiatRwf?.call(this) ?? orElse(this),
        FiatSar() => fiatSar?.call(this) ?? orElse(this),
        FiatSbd() => fiatSbd?.call(this) ?? orElse(this),
        FiatScr() => fiatScr?.call(this) ?? orElse(this),
        FiatSdg() => fiatSdg?.call(this) ?? orElse(this),
        FiatSek() => fiatSek?.call(this) ?? orElse(this),
        FiatSgd() => fiatSgd?.call(this) ?? orElse(this),
        FiatShp() => fiatShp?.call(this) ?? orElse(this),
        FiatSle() => fiatSle?.call(this) ?? orElse(this),
        FiatSll() => fiatSll?.call(this) ?? orElse(this),
        FiatSos() => fiatSos?.call(this) ?? orElse(this),
        FiatSrd() => fiatSrd?.call(this) ?? orElse(this),
        FiatSsp() => fiatSsp?.call(this) ?? orElse(this),
        FiatStn() => fiatStn?.call(this) ?? orElse(this),
        FiatSvc() => fiatSvc?.call(this) ?? orElse(this),
        FiatSyp() => fiatSyp?.call(this) ?? orElse(this),
        FiatSzl() => fiatSzl?.call(this) ?? orElse(this),
        FiatThb() => fiatThb?.call(this) ?? orElse(this),
        FiatTjs() => fiatTjs?.call(this) ?? orElse(this),
        FiatTmt() => fiatTmt?.call(this) ?? orElse(this),
        FiatTnd() => fiatTnd?.call(this) ?? orElse(this),
        FiatTop() => fiatTop?.call(this) ?? orElse(this),
        FiatTry() => fiatTry?.call(this) ?? orElse(this),
        FiatTtd() => fiatTtd?.call(this) ?? orElse(this),
        FiatTwd() => fiatTwd?.call(this) ?? orElse(this),
        FiatTzs() => fiatTzs?.call(this) ?? orElse(this),
        FiatUah() => fiatUah?.call(this) ?? orElse(this),
        FiatUgx() => fiatUgx?.call(this) ?? orElse(this),
        FiatUsd() => fiatUsd?.call(this) ?? orElse(this),
        FiatUyu() => fiatUyu?.call(this) ?? orElse(this),
        FiatUzs() => fiatUzs?.call(this) ?? orElse(this),
        FiatVes() => fiatVes?.call(this) ?? orElse(this),
        FiatVnd() => fiatVnd?.call(this) ?? orElse(this),
        FiatVuv() => fiatVuv?.call(this) ?? orElse(this),
        FiatWst() => fiatWst?.call(this) ?? orElse(this),
        FiatXaf() => fiatXaf?.call(this) ?? orElse(this),
        FiatXag() => fiatXag?.call(this) ?? orElse(this),
        FiatXau() => fiatXau?.call(this) ?? orElse(this),
        FiatXba() => fiatXba?.call(this) ?? orElse(this),
        FiatXbb() => fiatXbb?.call(this) ?? orElse(this),
        FiatXbc() => fiatXbc?.call(this) ?? orElse(this),
        FiatXbd() => fiatXbd?.call(this) ?? orElse(this),
        FiatXcd() => fiatXcd?.call(this) ?? orElse(this),
        FiatXdr() => fiatXdr?.call(this) ?? orElse(this),
        FiatXof() => fiatXof?.call(this) ?? orElse(this),
        FiatXpd() => fiatXpd?.call(this) ?? orElse(this),
        FiatXpf() => fiatXpf?.call(this) ?? orElse(this),
        FiatXpt() => fiatXpt?.call(this) ?? orElse(this),
        FiatXts() => fiatXts?.call(this) ?? orElse(this),
        FiatYer() => fiatYer?.call(this) ?? orElse(this),
        FiatZar() => fiatZar?.call(this) ?? orElse(this),
        FiatZwl() => fiatZwl?.call(this) ?? orElse(this),
        FiatZmw() => fiatZmw?.call(this) ?? orElse(this),
        _ => orElse(this),
      };

  R maybeWhen<R>({
    required R Function() orElse,
    R Function()? fiatAed,
    R Function()? fiatAfn,
    R Function()? fiatAll,
    R Function()? fiatAmd,
    R Function()? fiatAng,
    R Function()? fiatAoa,
    R Function()? fiatArs,
    R Function()? fiatAud,
    R Function()? fiatAwg,
    R Function()? fiatAzn,
    R Function()? fiatBam,
    R Function()? fiatBbd,
    R Function()? fiatBdt,
    R Function()? fiatBgn,
    R Function()? fiatBhd,
    R Function()? fiatBif,
    R Function()? fiatBmd,
    R Function()? fiatBnd,
    R Function()? fiatBob,
    R Function()? fiatBrl,
    R Function()? fiatBsd,
    R Function()? fiatBtn,
    R Function()? fiatBwp,
    R Function()? fiatByn,
    R Function()? fiatBzd,
    R Function()? fiatCad,
    R Function()? fiatCdf,
    R Function()? fiatChf,
    R Function()? fiatClf,
    R Function()? fiatClp,
    R Function()? fiatCny,
    R Function()? fiatCop,
    R Function()? fiatCrc,
    R Function()? fiatCuc,
    R Function()? fiatCup,
    R Function()? fiatCve,
    R Function()? fiatCzk,
    R Function()? fiatDjf,
    R Function()? fiatDkk,
    R Function()? fiatDop,
    R Function()? fiatDzd,
    R Function()? fiatEgp,
    R Function()? fiatErn,
    R Function()? fiatEtb,
    R Function()? fiatEur,
    R Function()? fiatFjd,
    R Function()? fiatFkp,
    R Function()? fiatGbp,
    R Function()? fiatGel,
    R Function()? fiatGhs,
    R Function()? fiatGip,
    R Function()? fiatGmd,
    R Function()? fiatGnf,
    R Function()? fiatGtq,
    R Function()? fiatGyd,
    R Function()? fiatHkd,
    R Function()? fiatHnl,
    R Function()? fiatHrk,
    R Function()? fiatHtg,
    R Function()? fiatHuf,
    R Function()? fiatIdr,
    R Function()? fiatIls,
    R Function()? fiatInr,
    R Function()? fiatIqd,
    R Function()? fiatIrr,
    R Function()? fiatIsk,
    R Function()? fiatJmd,
    R Function()? fiatJod,
    R Function()? fiatJpy,
    R Function()? fiatKes,
    R Function()? fiatKgs,
    R Function()? fiatKhr,
    R Function()? fiatKmf,
    R Function()? fiatKpw,
    R Function()? fiatKrw,
    R Function()? fiatKwd,
    R Function()? fiatKyd,
    R Function()? fiatKzt,
    R Function()? fiatLak,
    R Function()? fiatLbp,
    R Function()? fiatLkr,
    R Function()? fiatLrd,
    R Function()? fiatLsl,
    R Function()? fiatLyd,
    R Function()? fiatMad,
    R Function()? fiatMdl,
    R Function()? fiatMga,
    R Function()? fiatMkd,
    R Function()? fiatMmk,
    R Function()? fiatMnt,
    R Function()? fiatMop,
    R Function()? fiatMru,
    R Function()? fiatMur,
    R Function()? fiatMvr,
    R Function()? fiatMwk,
    R Function()? fiatMxn,
    R Function()? fiatMyr,
    R Function()? fiatMzn,
    R Function()? fiatNad,
    R Function()? fiatNgn,
    R Function()? fiatNio,
    R Function()? fiatNok,
    R Function()? fiatNpr,
    R Function()? fiatNzd,
    R Function()? fiatOmr,
    R Function()? fiatPab,
    R Function()? fiatPen,
    R Function()? fiatPgk,
    R Function()? fiatPhp,
    R Function()? fiatPkr,
    R Function()? fiatPln,
    R Function()? fiatPyg,
    R Function()? fiatQar,
    R Function()? fiatRon,
    R Function()? fiatRsd,
    R Function()? fiatRub,
    R Function()? fiatRwf,
    R Function()? fiatSar,
    R Function()? fiatSbd,
    R Function()? fiatScr,
    R Function()? fiatSdg,
    R Function()? fiatSek,
    R Function()? fiatSgd,
    R Function()? fiatShp,
    R Function()? fiatSle,
    R Function()? fiatSll,
    R Function()? fiatSos,
    R Function()? fiatSrd,
    R Function()? fiatSsp,
    R Function()? fiatStn,
    R Function()? fiatSvc,
    R Function()? fiatSyp,
    R Function()? fiatSzl,
    R Function()? fiatThb,
    R Function()? fiatTjs,
    R Function()? fiatTmt,
    R Function()? fiatTnd,
    R Function()? fiatTop,
    R Function()? fiatTry,
    R Function()? fiatTtd,
    R Function()? fiatTwd,
    R Function()? fiatTzs,
    R Function()? fiatUah,
    R Function()? fiatUgx,
    R Function()? fiatUsd,
    R Function()? fiatUyu,
    R Function()? fiatUzs,
    R Function()? fiatVes,
    R Function()? fiatVnd,
    R Function()? fiatVuv,
    R Function()? fiatWst,
    R Function()? fiatXaf,
    R Function()? fiatXag,
    R Function()? fiatXau,
    R Function()? fiatXba,
    R Function()? fiatXbb,
    R Function()? fiatXbc,
    R Function()? fiatXbd,
    R Function()? fiatXcd,
    R Function()? fiatXdr,
    R Function()? fiatXof,
    R Function()? fiatXpd,
    R Function()? fiatXpf,
    R Function()? fiatXpt,
    R Function()? fiatXts,
    R Function()? fiatYer,
    R Function()? fiatZar,
    R Function()? fiatZwl,
    R Function()? fiatZmw,
  }) =>
      switch (this) {
        FiatAed() => fiatAed?.call() ?? orElse(),
        FiatAfn() => fiatAfn?.call() ?? orElse(),
        FiatAll() => fiatAll?.call() ?? orElse(),
        FiatAmd() => fiatAmd?.call() ?? orElse(),
        FiatAng() => fiatAng?.call() ?? orElse(),
        FiatAoa() => fiatAoa?.call() ?? orElse(),
        FiatArs() => fiatArs?.call() ?? orElse(),
        FiatAud() => fiatAud?.call() ?? orElse(),
        FiatAwg() => fiatAwg?.call() ?? orElse(),
        FiatAzn() => fiatAzn?.call() ?? orElse(),
        FiatBam() => fiatBam?.call() ?? orElse(),
        FiatBbd() => fiatBbd?.call() ?? orElse(),
        FiatBdt() => fiatBdt?.call() ?? orElse(),
        FiatBgn() => fiatBgn?.call() ?? orElse(),
        FiatBhd() => fiatBhd?.call() ?? orElse(),
        FiatBif() => fiatBif?.call() ?? orElse(),
        FiatBmd() => fiatBmd?.call() ?? orElse(),
        FiatBnd() => fiatBnd?.call() ?? orElse(),
        FiatBob() => fiatBob?.call() ?? orElse(),
        FiatBrl() => fiatBrl?.call() ?? orElse(),
        FiatBsd() => fiatBsd?.call() ?? orElse(),
        FiatBtn() => fiatBtn?.call() ?? orElse(),
        FiatBwp() => fiatBwp?.call() ?? orElse(),
        FiatByn() => fiatByn?.call() ?? orElse(),
        FiatBzd() => fiatBzd?.call() ?? orElse(),
        FiatCad() => fiatCad?.call() ?? orElse(),
        FiatCdf() => fiatCdf?.call() ?? orElse(),
        FiatChf() => fiatChf?.call() ?? orElse(),
        FiatClf() => fiatClf?.call() ?? orElse(),
        FiatClp() => fiatClp?.call() ?? orElse(),
        FiatCny() => fiatCny?.call() ?? orElse(),
        FiatCop() => fiatCop?.call() ?? orElse(),
        FiatCrc() => fiatCrc?.call() ?? orElse(),
        FiatCuc() => fiatCuc?.call() ?? orElse(),
        FiatCup() => fiatCup?.call() ?? orElse(),
        FiatCve() => fiatCve?.call() ?? orElse(),
        FiatCzk() => fiatCzk?.call() ?? orElse(),
        FiatDjf() => fiatDjf?.call() ?? orElse(),
        FiatDkk() => fiatDkk?.call() ?? orElse(),
        FiatDop() => fiatDop?.call() ?? orElse(),
        FiatDzd() => fiatDzd?.call() ?? orElse(),
        FiatEgp() => fiatEgp?.call() ?? orElse(),
        FiatErn() => fiatErn?.call() ?? orElse(),
        FiatEtb() => fiatEtb?.call() ?? orElse(),
        FiatEur() => fiatEur?.call() ?? orElse(),
        FiatFjd() => fiatFjd?.call() ?? orElse(),
        FiatFkp() => fiatFkp?.call() ?? orElse(),
        FiatGbp() => fiatGbp?.call() ?? orElse(),
        FiatGel() => fiatGel?.call() ?? orElse(),
        FiatGhs() => fiatGhs?.call() ?? orElse(),
        FiatGip() => fiatGip?.call() ?? orElse(),
        FiatGmd() => fiatGmd?.call() ?? orElse(),
        FiatGnf() => fiatGnf?.call() ?? orElse(),
        FiatGtq() => fiatGtq?.call() ?? orElse(),
        FiatGyd() => fiatGyd?.call() ?? orElse(),
        FiatHkd() => fiatHkd?.call() ?? orElse(),
        FiatHnl() => fiatHnl?.call() ?? orElse(),
        FiatHrk() => fiatHrk?.call() ?? orElse(),
        FiatHtg() => fiatHtg?.call() ?? orElse(),
        FiatHuf() => fiatHuf?.call() ?? orElse(),
        FiatIdr() => fiatIdr?.call() ?? orElse(),
        FiatIls() => fiatIls?.call() ?? orElse(),
        FiatInr() => fiatInr?.call() ?? orElse(),
        FiatIqd() => fiatIqd?.call() ?? orElse(),
        FiatIrr() => fiatIrr?.call() ?? orElse(),
        FiatIsk() => fiatIsk?.call() ?? orElse(),
        FiatJmd() => fiatJmd?.call() ?? orElse(),
        FiatJod() => fiatJod?.call() ?? orElse(),
        FiatJpy() => fiatJpy?.call() ?? orElse(),
        FiatKes() => fiatKes?.call() ?? orElse(),
        FiatKgs() => fiatKgs?.call() ?? orElse(),
        FiatKhr() => fiatKhr?.call() ?? orElse(),
        FiatKmf() => fiatKmf?.call() ?? orElse(),
        FiatKpw() => fiatKpw?.call() ?? orElse(),
        FiatKrw() => fiatKrw?.call() ?? orElse(),
        FiatKwd() => fiatKwd?.call() ?? orElse(),
        FiatKyd() => fiatKyd?.call() ?? orElse(),
        FiatKzt() => fiatKzt?.call() ?? orElse(),
        FiatLak() => fiatLak?.call() ?? orElse(),
        FiatLbp() => fiatLbp?.call() ?? orElse(),
        FiatLkr() => fiatLkr?.call() ?? orElse(),
        FiatLrd() => fiatLrd?.call() ?? orElse(),
        FiatLsl() => fiatLsl?.call() ?? orElse(),
        FiatLyd() => fiatLyd?.call() ?? orElse(),
        FiatMad() => fiatMad?.call() ?? orElse(),
        FiatMdl() => fiatMdl?.call() ?? orElse(),
        FiatMga() => fiatMga?.call() ?? orElse(),
        FiatMkd() => fiatMkd?.call() ?? orElse(),
        FiatMmk() => fiatMmk?.call() ?? orElse(),
        FiatMnt() => fiatMnt?.call() ?? orElse(),
        FiatMop() => fiatMop?.call() ?? orElse(),
        FiatMru() => fiatMru?.call() ?? orElse(),
        FiatMur() => fiatMur?.call() ?? orElse(),
        FiatMvr() => fiatMvr?.call() ?? orElse(),
        FiatMwk() => fiatMwk?.call() ?? orElse(),
        FiatMxn() => fiatMxn?.call() ?? orElse(),
        FiatMyr() => fiatMyr?.call() ?? orElse(),
        FiatMzn() => fiatMzn?.call() ?? orElse(),
        FiatNad() => fiatNad?.call() ?? orElse(),
        FiatNgn() => fiatNgn?.call() ?? orElse(),
        FiatNio() => fiatNio?.call() ?? orElse(),
        FiatNok() => fiatNok?.call() ?? orElse(),
        FiatNpr() => fiatNpr?.call() ?? orElse(),
        FiatNzd() => fiatNzd?.call() ?? orElse(),
        FiatOmr() => fiatOmr?.call() ?? orElse(),
        FiatPab() => fiatPab?.call() ?? orElse(),
        FiatPen() => fiatPen?.call() ?? orElse(),
        FiatPgk() => fiatPgk?.call() ?? orElse(),
        FiatPhp() => fiatPhp?.call() ?? orElse(),
        FiatPkr() => fiatPkr?.call() ?? orElse(),
        FiatPln() => fiatPln?.call() ?? orElse(),
        FiatPyg() => fiatPyg?.call() ?? orElse(),
        FiatQar() => fiatQar?.call() ?? orElse(),
        FiatRon() => fiatRon?.call() ?? orElse(),
        FiatRsd() => fiatRsd?.call() ?? orElse(),
        FiatRub() => fiatRub?.call() ?? orElse(),
        FiatRwf() => fiatRwf?.call() ?? orElse(),
        FiatSar() => fiatSar?.call() ?? orElse(),
        FiatSbd() => fiatSbd?.call() ?? orElse(),
        FiatScr() => fiatScr?.call() ?? orElse(),
        FiatSdg() => fiatSdg?.call() ?? orElse(),
        FiatSek() => fiatSek?.call() ?? orElse(),
        FiatSgd() => fiatSgd?.call() ?? orElse(),
        FiatShp() => fiatShp?.call() ?? orElse(),
        FiatSle() => fiatSle?.call() ?? orElse(),
        FiatSll() => fiatSll?.call() ?? orElse(),
        FiatSos() => fiatSos?.call() ?? orElse(),
        FiatSrd() => fiatSrd?.call() ?? orElse(),
        FiatSsp() => fiatSsp?.call() ?? orElse(),
        FiatStn() => fiatStn?.call() ?? orElse(),
        FiatSvc() => fiatSvc?.call() ?? orElse(),
        FiatSyp() => fiatSyp?.call() ?? orElse(),
        FiatSzl() => fiatSzl?.call() ?? orElse(),
        FiatThb() => fiatThb?.call() ?? orElse(),
        FiatTjs() => fiatTjs?.call() ?? orElse(),
        FiatTmt() => fiatTmt?.call() ?? orElse(),
        FiatTnd() => fiatTnd?.call() ?? orElse(),
        FiatTop() => fiatTop?.call() ?? orElse(),
        FiatTry() => fiatTry?.call() ?? orElse(),
        FiatTtd() => fiatTtd?.call() ?? orElse(),
        FiatTwd() => fiatTwd?.call() ?? orElse(),
        FiatTzs() => fiatTzs?.call() ?? orElse(),
        FiatUah() => fiatUah?.call() ?? orElse(),
        FiatUgx() => fiatUgx?.call() ?? orElse(),
        FiatUsd() => fiatUsd?.call() ?? orElse(),
        FiatUyu() => fiatUyu?.call() ?? orElse(),
        FiatUzs() => fiatUzs?.call() ?? orElse(),
        FiatVes() => fiatVes?.call() ?? orElse(),
        FiatVnd() => fiatVnd?.call() ?? orElse(),
        FiatVuv() => fiatVuv?.call() ?? orElse(),
        FiatWst() => fiatWst?.call() ?? orElse(),
        FiatXaf() => fiatXaf?.call() ?? orElse(),
        FiatXag() => fiatXag?.call() ?? orElse(),
        FiatXau() => fiatXau?.call() ?? orElse(),
        FiatXba() => fiatXba?.call() ?? orElse(),
        FiatXbb() => fiatXbb?.call() ?? orElse(),
        FiatXbc() => fiatXbc?.call() ?? orElse(),
        FiatXbd() => fiatXbd?.call() ?? orElse(),
        FiatXcd() => fiatXcd?.call() ?? orElse(),
        FiatXdr() => fiatXdr?.call() ?? orElse(),
        FiatXof() => fiatXof?.call() ?? orElse(),
        FiatXpd() => fiatXpd?.call() ?? orElse(),
        FiatXpf() => fiatXpf?.call() ?? orElse(),
        FiatXpt() => fiatXpt?.call() ?? orElse(),
        FiatXts() => fiatXts?.call() ?? orElse(),
        FiatYer() => fiatYer?.call() ?? orElse(),
        FiatZar() => fiatZar?.call() ?? orElse(),
        FiatZwl() => fiatZwl?.call() ?? orElse(),
        FiatZmw() => fiatZmw?.call() ?? orElse(),
        _ => orElse(),
      };

  R when<R>({
    required R Function() fiatAed,
    required R Function() fiatAfn,
    required R Function() fiatAll,
    required R Function() fiatAmd,
    required R Function() fiatAng,
    required R Function() fiatAoa,
    required R Function() fiatArs,
    required R Function() fiatAud,
    required R Function() fiatAwg,
    required R Function() fiatAzn,
    required R Function() fiatBam,
    required R Function() fiatBbd,
    required R Function() fiatBdt,
    required R Function() fiatBgn,
    required R Function() fiatBhd,
    required R Function() fiatBif,
    required R Function() fiatBmd,
    required R Function() fiatBnd,
    required R Function() fiatBob,
    required R Function() fiatBrl,
    required R Function() fiatBsd,
    required R Function() fiatBtn,
    required R Function() fiatBwp,
    required R Function() fiatByn,
    required R Function() fiatBzd,
    required R Function() fiatCad,
    required R Function() fiatCdf,
    required R Function() fiatChf,
    required R Function() fiatClf,
    required R Function() fiatClp,
    required R Function() fiatCny,
    required R Function() fiatCop,
    required R Function() fiatCrc,
    required R Function() fiatCuc,
    required R Function() fiatCup,
    required R Function() fiatCve,
    required R Function() fiatCzk,
    required R Function() fiatDjf,
    required R Function() fiatDkk,
    required R Function() fiatDop,
    required R Function() fiatDzd,
    required R Function() fiatEgp,
    required R Function() fiatErn,
    required R Function() fiatEtb,
    required R Function() fiatEur,
    required R Function() fiatFjd,
    required R Function() fiatFkp,
    required R Function() fiatGbp,
    required R Function() fiatGel,
    required R Function() fiatGhs,
    required R Function() fiatGip,
    required R Function() fiatGmd,
    required R Function() fiatGnf,
    required R Function() fiatGtq,
    required R Function() fiatGyd,
    required R Function() fiatHkd,
    required R Function() fiatHnl,
    required R Function() fiatHrk,
    required R Function() fiatHtg,
    required R Function() fiatHuf,
    required R Function() fiatIdr,
    required R Function() fiatIls,
    required R Function() fiatInr,
    required R Function() fiatIqd,
    required R Function() fiatIrr,
    required R Function() fiatIsk,
    required R Function() fiatJmd,
    required R Function() fiatJod,
    required R Function() fiatJpy,
    required R Function() fiatKes,
    required R Function() fiatKgs,
    required R Function() fiatKhr,
    required R Function() fiatKmf,
    required R Function() fiatKpw,
    required R Function() fiatKrw,
    required R Function() fiatKwd,
    required R Function() fiatKyd,
    required R Function() fiatKzt,
    required R Function() fiatLak,
    required R Function() fiatLbp,
    required R Function() fiatLkr,
    required R Function() fiatLrd,
    required R Function() fiatLsl,
    required R Function() fiatLyd,
    required R Function() fiatMad,
    required R Function() fiatMdl,
    required R Function() fiatMga,
    required R Function() fiatMkd,
    required R Function() fiatMmk,
    required R Function() fiatMnt,
    required R Function() fiatMop,
    required R Function() fiatMru,
    required R Function() fiatMur,
    required R Function() fiatMvr,
    required R Function() fiatMwk,
    required R Function() fiatMxn,
    required R Function() fiatMyr,
    required R Function() fiatMzn,
    required R Function() fiatNad,
    required R Function() fiatNgn,
    required R Function() fiatNio,
    required R Function() fiatNok,
    required R Function() fiatNpr,
    required R Function() fiatNzd,
    required R Function() fiatOmr,
    required R Function() fiatPab,
    required R Function() fiatPen,
    required R Function() fiatPgk,
    required R Function() fiatPhp,
    required R Function() fiatPkr,
    required R Function() fiatPln,
    required R Function() fiatPyg,
    required R Function() fiatQar,
    required R Function() fiatRon,
    required R Function() fiatRsd,
    required R Function() fiatRub,
    required R Function() fiatRwf,
    required R Function() fiatSar,
    required R Function() fiatSbd,
    required R Function() fiatScr,
    required R Function() fiatSdg,
    required R Function() fiatSek,
    required R Function() fiatSgd,
    required R Function() fiatShp,
    required R Function() fiatSle,
    required R Function() fiatSll,
    required R Function() fiatSos,
    required R Function() fiatSrd,
    required R Function() fiatSsp,
    required R Function() fiatStn,
    required R Function() fiatSvc,
    required R Function() fiatSyp,
    required R Function() fiatSzl,
    required R Function() fiatThb,
    required R Function() fiatTjs,
    required R Function() fiatTmt,
    required R Function() fiatTnd,
    required R Function() fiatTop,
    required R Function() fiatTry,
    required R Function() fiatTtd,
    required R Function() fiatTwd,
    required R Function() fiatTzs,
    required R Function() fiatUah,
    required R Function() fiatUgx,
    required R Function() fiatUsd,
    required R Function() fiatUyu,
    required R Function() fiatUzs,
    required R Function() fiatVes,
    required R Function() fiatVnd,
    required R Function() fiatVuv,
    required R Function() fiatWst,
    required R Function() fiatXaf,
    required R Function() fiatXag,
    required R Function() fiatXau,
    required R Function() fiatXba,
    required R Function() fiatXbb,
    required R Function() fiatXbc,
    required R Function() fiatXbd,
    required R Function() fiatXcd,
    required R Function() fiatXdr,
    required R Function() fiatXof,
    required R Function() fiatXpd,
    required R Function() fiatXpf,
    required R Function() fiatXpt,
    required R Function() fiatXts,
    required R Function() fiatYer,
    required R Function() fiatZar,
    required R Function() fiatZwl,
    required R Function() fiatZmw,
  }) =>
      switch (this) {
        FiatAed() => fiatAed(),
        FiatAfn() => fiatAfn(),
        FiatAll() => fiatAll(),
        FiatAmd() => fiatAmd(),
        FiatAng() => fiatAng(),
        FiatAoa() => fiatAoa(),
        FiatArs() => fiatArs(),
        FiatAud() => fiatAud(),
        FiatAwg() => fiatAwg(),
        FiatAzn() => fiatAzn(),
        FiatBam() => fiatBam(),
        FiatBbd() => fiatBbd(),
        FiatBdt() => fiatBdt(),
        FiatBgn() => fiatBgn(),
        FiatBhd() => fiatBhd(),
        FiatBif() => fiatBif(),
        FiatBmd() => fiatBmd(),
        FiatBnd() => fiatBnd(),
        FiatBob() => fiatBob(),
        FiatBrl() => fiatBrl(),
        FiatBsd() => fiatBsd(),
        FiatBtn() => fiatBtn(),
        FiatBwp() => fiatBwp(),
        FiatByn() => fiatByn(),
        FiatBzd() => fiatBzd(),
        FiatCad() => fiatCad(),
        FiatCdf() => fiatCdf(),
        FiatChf() => fiatChf(),
        FiatClf() => fiatClf(),
        FiatClp() => fiatClp(),
        FiatCny() => fiatCny(),
        FiatCop() => fiatCop(),
        FiatCrc() => fiatCrc(),
        FiatCuc() => fiatCuc(),
        FiatCup() => fiatCup(),
        FiatCve() => fiatCve(),
        FiatCzk() => fiatCzk(),
        FiatDjf() => fiatDjf(),
        FiatDkk() => fiatDkk(),
        FiatDop() => fiatDop(),
        FiatDzd() => fiatDzd(),
        FiatEgp() => fiatEgp(),
        FiatErn() => fiatErn(),
        FiatEtb() => fiatEtb(),
        FiatEur() => fiatEur(),
        FiatFjd() => fiatFjd(),
        FiatFkp() => fiatFkp(),
        FiatGbp() => fiatGbp(),
        FiatGel() => fiatGel(),
        FiatGhs() => fiatGhs(),
        FiatGip() => fiatGip(),
        FiatGmd() => fiatGmd(),
        FiatGnf() => fiatGnf(),
        FiatGtq() => fiatGtq(),
        FiatGyd() => fiatGyd(),
        FiatHkd() => fiatHkd(),
        FiatHnl() => fiatHnl(),
        FiatHrk() => fiatHrk(),
        FiatHtg() => fiatHtg(),
        FiatHuf() => fiatHuf(),
        FiatIdr() => fiatIdr(),
        FiatIls() => fiatIls(),
        FiatInr() => fiatInr(),
        FiatIqd() => fiatIqd(),
        FiatIrr() => fiatIrr(),
        FiatIsk() => fiatIsk(),
        FiatJmd() => fiatJmd(),
        FiatJod() => fiatJod(),
        FiatJpy() => fiatJpy(),
        FiatKes() => fiatKes(),
        FiatKgs() => fiatKgs(),
        FiatKhr() => fiatKhr(),
        FiatKmf() => fiatKmf(),
        FiatKpw() => fiatKpw(),
        FiatKrw() => fiatKrw(),
        FiatKwd() => fiatKwd(),
        FiatKyd() => fiatKyd(),
        FiatKzt() => fiatKzt(),
        FiatLak() => fiatLak(),
        FiatLbp() => fiatLbp(),
        FiatLkr() => fiatLkr(),
        FiatLrd() => fiatLrd(),
        FiatLsl() => fiatLsl(),
        FiatLyd() => fiatLyd(),
        FiatMad() => fiatMad(),
        FiatMdl() => fiatMdl(),
        FiatMga() => fiatMga(),
        FiatMkd() => fiatMkd(),
        FiatMmk() => fiatMmk(),
        FiatMnt() => fiatMnt(),
        FiatMop() => fiatMop(),
        FiatMru() => fiatMru(),
        FiatMur() => fiatMur(),
        FiatMvr() => fiatMvr(),
        FiatMwk() => fiatMwk(),
        FiatMxn() => fiatMxn(),
        FiatMyr() => fiatMyr(),
        FiatMzn() => fiatMzn(),
        FiatNad() => fiatNad(),
        FiatNgn() => fiatNgn(),
        FiatNio() => fiatNio(),
        FiatNok() => fiatNok(),
        FiatNpr() => fiatNpr(),
        FiatNzd() => fiatNzd(),
        FiatOmr() => fiatOmr(),
        FiatPab() => fiatPab(),
        FiatPen() => fiatPen(),
        FiatPgk() => fiatPgk(),
        FiatPhp() => fiatPhp(),
        FiatPkr() => fiatPkr(),
        FiatPln() => fiatPln(),
        FiatPyg() => fiatPyg(),
        FiatQar() => fiatQar(),
        FiatRon() => fiatRon(),
        FiatRsd() => fiatRsd(),
        FiatRub() => fiatRub(),
        FiatRwf() => fiatRwf(),
        FiatSar() => fiatSar(),
        FiatSbd() => fiatSbd(),
        FiatScr() => fiatScr(),
        FiatSdg() => fiatSdg(),
        FiatSek() => fiatSek(),
        FiatSgd() => fiatSgd(),
        FiatShp() => fiatShp(),
        FiatSle() => fiatSle(),
        FiatSll() => fiatSll(),
        FiatSos() => fiatSos(),
        FiatSrd() => fiatSrd(),
        FiatSsp() => fiatSsp(),
        FiatStn() => fiatStn(),
        FiatSvc() => fiatSvc(),
        FiatSyp() => fiatSyp(),
        FiatSzl() => fiatSzl(),
        FiatThb() => fiatThb(),
        FiatTjs() => fiatTjs(),
        FiatTmt() => fiatTmt(),
        FiatTnd() => fiatTnd(),
        FiatTop() => fiatTop(),
        FiatTry() => fiatTry(),
        FiatTtd() => fiatTtd(),
        FiatTwd() => fiatTwd(),
        FiatTzs() => fiatTzs(),
        FiatUah() => fiatUah(),
        FiatUgx() => fiatUgx(),
        FiatUsd() => fiatUsd(),
        FiatUyu() => fiatUyu(),
        FiatUzs() => fiatUzs(),
        FiatVes() => fiatVes(),
        FiatVnd() => fiatVnd(),
        FiatVuv() => fiatVuv(),
        FiatWst() => fiatWst(),
        FiatXaf() => fiatXaf(),
        FiatXag() => fiatXag(),
        FiatXau() => fiatXau(),
        FiatXba() => fiatXba(),
        FiatXbb() => fiatXbb(),
        FiatXbc() => fiatXbc(),
        FiatXbd() => fiatXbd(),
        FiatXcd() => fiatXcd(),
        FiatXdr() => fiatXdr(),
        FiatXof() => fiatXof(),
        FiatXpd() => fiatXpd(),
        FiatXpf() => fiatXpf(),
        FiatXpt() => fiatXpt(),
        FiatXts() => fiatXts(),
        FiatYer() => fiatYer(),
        FiatZar() => fiatZar(),
        FiatZwl() => fiatZwl(),
        FiatZmw() => fiatZmw(),
        _ => throw ArgumentError("Unknown value: $this", name),
      };

  R? whenOrNull<R>({
    R Function()? fiatAed,
    R Function()? fiatAfn,
    R Function()? fiatAll,
    R Function()? fiatAmd,
    R Function()? fiatAng,
    R Function()? fiatAoa,
    R Function()? fiatArs,
    R Function()? fiatAud,
    R Function()? fiatAwg,
    R Function()? fiatAzn,
    R Function()? fiatBam,
    R Function()? fiatBbd,
    R Function()? fiatBdt,
    R Function()? fiatBgn,
    R Function()? fiatBhd,
    R Function()? fiatBif,
    R Function()? fiatBmd,
    R Function()? fiatBnd,
    R Function()? fiatBob,
    R Function()? fiatBrl,
    R Function()? fiatBsd,
    R Function()? fiatBtn,
    R Function()? fiatBwp,
    R Function()? fiatByn,
    R Function()? fiatBzd,
    R Function()? fiatCad,
    R Function()? fiatCdf,
    R Function()? fiatChf,
    R Function()? fiatClf,
    R Function()? fiatClp,
    R Function()? fiatCny,
    R Function()? fiatCop,
    R Function()? fiatCrc,
    R Function()? fiatCuc,
    R Function()? fiatCup,
    R Function()? fiatCve,
    R Function()? fiatCzk,
    R Function()? fiatDjf,
    R Function()? fiatDkk,
    R Function()? fiatDop,
    R Function()? fiatDzd,
    R Function()? fiatEgp,
    R Function()? fiatErn,
    R Function()? fiatEtb,
    R Function()? fiatEur,
    R Function()? fiatFjd,
    R Function()? fiatFkp,
    R Function()? fiatGbp,
    R Function()? fiatGel,
    R Function()? fiatGhs,
    R Function()? fiatGip,
    R Function()? fiatGmd,
    R Function()? fiatGnf,
    R Function()? fiatGtq,
    R Function()? fiatGyd,
    R Function()? fiatHkd,
    R Function()? fiatHnl,
    R Function()? fiatHrk,
    R Function()? fiatHtg,
    R Function()? fiatHuf,
    R Function()? fiatIdr,
    R Function()? fiatIls,
    R Function()? fiatInr,
    R Function()? fiatIqd,
    R Function()? fiatIrr,
    R Function()? fiatIsk,
    R Function()? fiatJmd,
    R Function()? fiatJod,
    R Function()? fiatJpy,
    R Function()? fiatKes,
    R Function()? fiatKgs,
    R Function()? fiatKhr,
    R Function()? fiatKmf,
    R Function()? fiatKpw,
    R Function()? fiatKrw,
    R Function()? fiatKwd,
    R Function()? fiatKyd,
    R Function()? fiatKzt,
    R Function()? fiatLak,
    R Function()? fiatLbp,
    R Function()? fiatLkr,
    R Function()? fiatLrd,
    R Function()? fiatLsl,
    R Function()? fiatLyd,
    R Function()? fiatMad,
    R Function()? fiatMdl,
    R Function()? fiatMga,
    R Function()? fiatMkd,
    R Function()? fiatMmk,
    R Function()? fiatMnt,
    R Function()? fiatMop,
    R Function()? fiatMru,
    R Function()? fiatMur,
    R Function()? fiatMvr,
    R Function()? fiatMwk,
    R Function()? fiatMxn,
    R Function()? fiatMyr,
    R Function()? fiatMzn,
    R Function()? fiatNad,
    R Function()? fiatNgn,
    R Function()? fiatNio,
    R Function()? fiatNok,
    R Function()? fiatNpr,
    R Function()? fiatNzd,
    R Function()? fiatOmr,
    R Function()? fiatPab,
    R Function()? fiatPen,
    R Function()? fiatPgk,
    R Function()? fiatPhp,
    R Function()? fiatPkr,
    R Function()? fiatPln,
    R Function()? fiatPyg,
    R Function()? fiatQar,
    R Function()? fiatRon,
    R Function()? fiatRsd,
    R Function()? fiatRub,
    R Function()? fiatRwf,
    R Function()? fiatSar,
    R Function()? fiatSbd,
    R Function()? fiatScr,
    R Function()? fiatSdg,
    R Function()? fiatSek,
    R Function()? fiatSgd,
    R Function()? fiatShp,
    R Function()? fiatSle,
    R Function()? fiatSll,
    R Function()? fiatSos,
    R Function()? fiatSrd,
    R Function()? fiatSsp,
    R Function()? fiatStn,
    R Function()? fiatSvc,
    R Function()? fiatSyp,
    R Function()? fiatSzl,
    R Function()? fiatThb,
    R Function()? fiatTjs,
    R Function()? fiatTmt,
    R Function()? fiatTnd,
    R Function()? fiatTop,
    R Function()? fiatTry,
    R Function()? fiatTtd,
    R Function()? fiatTwd,
    R Function()? fiatTzs,
    R Function()? fiatUah,
    R Function()? fiatUgx,
    R Function()? fiatUsd,
    R Function()? fiatUyu,
    R Function()? fiatUzs,
    R Function()? fiatVes,
    R Function()? fiatVnd,
    R Function()? fiatVuv,
    R Function()? fiatWst,
    R Function()? fiatXaf,
    R Function()? fiatXag,
    R Function()? fiatXau,
    R Function()? fiatXba,
    R Function()? fiatXbb,
    R Function()? fiatXbc,
    R Function()? fiatXbd,
    R Function()? fiatXcd,
    R Function()? fiatXdr,
    R Function()? fiatXof,
    R Function()? fiatXpd,
    R Function()? fiatXpf,
    R Function()? fiatXpt,
    R Function()? fiatXts,
    R Function()? fiatYer,
    R Function()? fiatZar,
    R Function()? fiatZwl,
    R Function()? fiatZmw,
    R Function()? orElse,
  }) =>
      switch (this) {
        FiatAed() => fiatAed?.call() ?? orElse?.call(),
        FiatAfn() => fiatAfn?.call() ?? orElse?.call(),
        FiatAll() => fiatAll?.call() ?? orElse?.call(),
        FiatAmd() => fiatAmd?.call() ?? orElse?.call(),
        FiatAng() => fiatAng?.call() ?? orElse?.call(),
        FiatAoa() => fiatAoa?.call() ?? orElse?.call(),
        FiatArs() => fiatArs?.call() ?? orElse?.call(),
        FiatAud() => fiatAud?.call() ?? orElse?.call(),
        FiatAwg() => fiatAwg?.call() ?? orElse?.call(),
        FiatAzn() => fiatAzn?.call() ?? orElse?.call(),
        FiatBam() => fiatBam?.call() ?? orElse?.call(),
        FiatBbd() => fiatBbd?.call() ?? orElse?.call(),
        FiatBdt() => fiatBdt?.call() ?? orElse?.call(),
        FiatBgn() => fiatBgn?.call() ?? orElse?.call(),
        FiatBhd() => fiatBhd?.call() ?? orElse?.call(),
        FiatBif() => fiatBif?.call() ?? orElse?.call(),
        FiatBmd() => fiatBmd?.call() ?? orElse?.call(),
        FiatBnd() => fiatBnd?.call() ?? orElse?.call(),
        FiatBob() => fiatBob?.call() ?? orElse?.call(),
        FiatBrl() => fiatBrl?.call() ?? orElse?.call(),
        FiatBsd() => fiatBsd?.call() ?? orElse?.call(),
        FiatBtn() => fiatBtn?.call() ?? orElse?.call(),
        FiatBwp() => fiatBwp?.call() ?? orElse?.call(),
        FiatByn() => fiatByn?.call() ?? orElse?.call(),
        FiatBzd() => fiatBzd?.call() ?? orElse?.call(),
        FiatCad() => fiatCad?.call() ?? orElse?.call(),
        FiatCdf() => fiatCdf?.call() ?? orElse?.call(),
        FiatChf() => fiatChf?.call() ?? orElse?.call(),
        FiatClf() => fiatClf?.call() ?? orElse?.call(),
        FiatClp() => fiatClp?.call() ?? orElse?.call(),
        FiatCny() => fiatCny?.call() ?? orElse?.call(),
        FiatCop() => fiatCop?.call() ?? orElse?.call(),
        FiatCrc() => fiatCrc?.call() ?? orElse?.call(),
        FiatCuc() => fiatCuc?.call() ?? orElse?.call(),
        FiatCup() => fiatCup?.call() ?? orElse?.call(),
        FiatCve() => fiatCve?.call() ?? orElse?.call(),
        FiatCzk() => fiatCzk?.call() ?? orElse?.call(),
        FiatDjf() => fiatDjf?.call() ?? orElse?.call(),
        FiatDkk() => fiatDkk?.call() ?? orElse?.call(),
        FiatDop() => fiatDop?.call() ?? orElse?.call(),
        FiatDzd() => fiatDzd?.call() ?? orElse?.call(),
        FiatEgp() => fiatEgp?.call() ?? orElse?.call(),
        FiatErn() => fiatErn?.call() ?? orElse?.call(),
        FiatEtb() => fiatEtb?.call() ?? orElse?.call(),
        FiatEur() => fiatEur?.call() ?? orElse?.call(),
        FiatFjd() => fiatFjd?.call() ?? orElse?.call(),
        FiatFkp() => fiatFkp?.call() ?? orElse?.call(),
        FiatGbp() => fiatGbp?.call() ?? orElse?.call(),
        FiatGel() => fiatGel?.call() ?? orElse?.call(),
        FiatGhs() => fiatGhs?.call() ?? orElse?.call(),
        FiatGip() => fiatGip?.call() ?? orElse?.call(),
        FiatGmd() => fiatGmd?.call() ?? orElse?.call(),
        FiatGnf() => fiatGnf?.call() ?? orElse?.call(),
        FiatGtq() => fiatGtq?.call() ?? orElse?.call(),
        FiatGyd() => fiatGyd?.call() ?? orElse?.call(),
        FiatHkd() => fiatHkd?.call() ?? orElse?.call(),
        FiatHnl() => fiatHnl?.call() ?? orElse?.call(),
        FiatHrk() => fiatHrk?.call() ?? orElse?.call(),
        FiatHtg() => fiatHtg?.call() ?? orElse?.call(),
        FiatHuf() => fiatHuf?.call() ?? orElse?.call(),
        FiatIdr() => fiatIdr?.call() ?? orElse?.call(),
        FiatIls() => fiatIls?.call() ?? orElse?.call(),
        FiatInr() => fiatInr?.call() ?? orElse?.call(),
        FiatIqd() => fiatIqd?.call() ?? orElse?.call(),
        FiatIrr() => fiatIrr?.call() ?? orElse?.call(),
        FiatIsk() => fiatIsk?.call() ?? orElse?.call(),
        FiatJmd() => fiatJmd?.call() ?? orElse?.call(),
        FiatJod() => fiatJod?.call() ?? orElse?.call(),
        FiatJpy() => fiatJpy?.call() ?? orElse?.call(),
        FiatKes() => fiatKes?.call() ?? orElse?.call(),
        FiatKgs() => fiatKgs?.call() ?? orElse?.call(),
        FiatKhr() => fiatKhr?.call() ?? orElse?.call(),
        FiatKmf() => fiatKmf?.call() ?? orElse?.call(),
        FiatKpw() => fiatKpw?.call() ?? orElse?.call(),
        FiatKrw() => fiatKrw?.call() ?? orElse?.call(),
        FiatKwd() => fiatKwd?.call() ?? orElse?.call(),
        FiatKyd() => fiatKyd?.call() ?? orElse?.call(),
        FiatKzt() => fiatKzt?.call() ?? orElse?.call(),
        FiatLak() => fiatLak?.call() ?? orElse?.call(),
        FiatLbp() => fiatLbp?.call() ?? orElse?.call(),
        FiatLkr() => fiatLkr?.call() ?? orElse?.call(),
        FiatLrd() => fiatLrd?.call() ?? orElse?.call(),
        FiatLsl() => fiatLsl?.call() ?? orElse?.call(),
        FiatLyd() => fiatLyd?.call() ?? orElse?.call(),
        FiatMad() => fiatMad?.call() ?? orElse?.call(),
        FiatMdl() => fiatMdl?.call() ?? orElse?.call(),
        FiatMga() => fiatMga?.call() ?? orElse?.call(),
        FiatMkd() => fiatMkd?.call() ?? orElse?.call(),
        FiatMmk() => fiatMmk?.call() ?? orElse?.call(),
        FiatMnt() => fiatMnt?.call() ?? orElse?.call(),
        FiatMop() => fiatMop?.call() ?? orElse?.call(),
        FiatMru() => fiatMru?.call() ?? orElse?.call(),
        FiatMur() => fiatMur?.call() ?? orElse?.call(),
        FiatMvr() => fiatMvr?.call() ?? orElse?.call(),
        FiatMwk() => fiatMwk?.call() ?? orElse?.call(),
        FiatMxn() => fiatMxn?.call() ?? orElse?.call(),
        FiatMyr() => fiatMyr?.call() ?? orElse?.call(),
        FiatMzn() => fiatMzn?.call() ?? orElse?.call(),
        FiatNad() => fiatNad?.call() ?? orElse?.call(),
        FiatNgn() => fiatNgn?.call() ?? orElse?.call(),
        FiatNio() => fiatNio?.call() ?? orElse?.call(),
        FiatNok() => fiatNok?.call() ?? orElse?.call(),
        FiatNpr() => fiatNpr?.call() ?? orElse?.call(),
        FiatNzd() => fiatNzd?.call() ?? orElse?.call(),
        FiatOmr() => fiatOmr?.call() ?? orElse?.call(),
        FiatPab() => fiatPab?.call() ?? orElse?.call(),
        FiatPen() => fiatPen?.call() ?? orElse?.call(),
        FiatPgk() => fiatPgk?.call() ?? orElse?.call(),
        FiatPhp() => fiatPhp?.call() ?? orElse?.call(),
        FiatPkr() => fiatPkr?.call() ?? orElse?.call(),
        FiatPln() => fiatPln?.call() ?? orElse?.call(),
        FiatPyg() => fiatPyg?.call() ?? orElse?.call(),
        FiatQar() => fiatQar?.call() ?? orElse?.call(),
        FiatRon() => fiatRon?.call() ?? orElse?.call(),
        FiatRsd() => fiatRsd?.call() ?? orElse?.call(),
        FiatRub() => fiatRub?.call() ?? orElse?.call(),
        FiatRwf() => fiatRwf?.call() ?? orElse?.call(),
        FiatSar() => fiatSar?.call() ?? orElse?.call(),
        FiatSbd() => fiatSbd?.call() ?? orElse?.call(),
        FiatScr() => fiatScr?.call() ?? orElse?.call(),
        FiatSdg() => fiatSdg?.call() ?? orElse?.call(),
        FiatSek() => fiatSek?.call() ?? orElse?.call(),
        FiatSgd() => fiatSgd?.call() ?? orElse?.call(),
        FiatShp() => fiatShp?.call() ?? orElse?.call(),
        FiatSle() => fiatSle?.call() ?? orElse?.call(),
        FiatSll() => fiatSll?.call() ?? orElse?.call(),
        FiatSos() => fiatSos?.call() ?? orElse?.call(),
        FiatSrd() => fiatSrd?.call() ?? orElse?.call(),
        FiatSsp() => fiatSsp?.call() ?? orElse?.call(),
        FiatStn() => fiatStn?.call() ?? orElse?.call(),
        FiatSvc() => fiatSvc?.call() ?? orElse?.call(),
        FiatSyp() => fiatSyp?.call() ?? orElse?.call(),
        FiatSzl() => fiatSzl?.call() ?? orElse?.call(),
        FiatThb() => fiatThb?.call() ?? orElse?.call(),
        FiatTjs() => fiatTjs?.call() ?? orElse?.call(),
        FiatTmt() => fiatTmt?.call() ?? orElse?.call(),
        FiatTnd() => fiatTnd?.call() ?? orElse?.call(),
        FiatTop() => fiatTop?.call() ?? orElse?.call(),
        FiatTry() => fiatTry?.call() ?? orElse?.call(),
        FiatTtd() => fiatTtd?.call() ?? orElse?.call(),
        FiatTwd() => fiatTwd?.call() ?? orElse?.call(),
        FiatTzs() => fiatTzs?.call() ?? orElse?.call(),
        FiatUah() => fiatUah?.call() ?? orElse?.call(),
        FiatUgx() => fiatUgx?.call() ?? orElse?.call(),
        FiatUsd() => fiatUsd?.call() ?? orElse?.call(),
        FiatUyu() => fiatUyu?.call() ?? orElse?.call(),
        FiatUzs() => fiatUzs?.call() ?? orElse?.call(),
        FiatVes() => fiatVes?.call() ?? orElse?.call(),
        FiatVnd() => fiatVnd?.call() ?? orElse?.call(),
        FiatVuv() => fiatVuv?.call() ?? orElse?.call(),
        FiatWst() => fiatWst?.call() ?? orElse?.call(),
        FiatXaf() => fiatXaf?.call() ?? orElse?.call(),
        FiatXag() => fiatXag?.call() ?? orElse?.call(),
        FiatXau() => fiatXau?.call() ?? orElse?.call(),
        FiatXba() => fiatXba?.call() ?? orElse?.call(),
        FiatXbb() => fiatXbb?.call() ?? orElse?.call(),
        FiatXbc() => fiatXbc?.call() ?? orElse?.call(),
        FiatXbd() => fiatXbd?.call() ?? orElse?.call(),
        FiatXcd() => fiatXcd?.call() ?? orElse?.call(),
        FiatXdr() => fiatXdr?.call() ?? orElse?.call(),
        FiatXof() => fiatXof?.call() ?? orElse?.call(),
        FiatXpd() => fiatXpd?.call() ?? orElse?.call(),
        FiatXpf() => fiatXpf?.call() ?? orElse?.call(),
        FiatXpt() => fiatXpt?.call() ?? orElse?.call(),
        FiatXts() => fiatXts?.call() ?? orElse?.call(),
        FiatYer() => fiatYer?.call() ?? orElse?.call(),
        FiatZar() => fiatZar?.call() ?? orElse?.call(),
        FiatZwl() => fiatZwl?.call() ?? orElse?.call(),
        FiatZmw() => fiatZmw?.call() ?? orElse?.call(),
        _ => orElse?.call(),
      };
}
