include: ../analysis_options.yaml

dart_code_metrics:
  rules:
    - always-remove-listener: true
    - avoid-border-all: true
    - avoid-expanded-as-spacer: true
    - avoid-returning-widgets: true
    - avoid-shrink-wrap-in-lists: true
    - avoid-unnecessary-setstate: true
    - avoid-wrapping-in-padding: true
    - check-for-equals-in-render-object-setters: true
    - consistent-update-render-object: true
    - prefer-const-border-radius: true
    - prefer-correct-edge-insets-constructor: true
    - prefer-extracting-callbacks: true
    - prefer-intl-name: true
    - prefer-single-widget-per-file: true
    - prefer-using-list-view: true
    - provide-correct-intl-args: true
    - use-setstate-synchronously: true

linter:
  rules:
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true