include: ../packages/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false

dart_code_metrics:
  rules:
    - prefer-moving-to-variable:
        allowed-duplicated-chains: 3
    - prefer-correct-identifier-length:
        # i for index, x for math operations, sb for StringBuffer, io for IO.
        exceptions: ["i", "io", "x", "sb"]