// elements.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'custom_elements_properties.dart';
export 'elements_properties.dart';