// ignore_for_file: depend_on_referenced_packages

import "package:flags/src/data/flags_map_part_1.data.dart";
import "package:flags/src/data/flags_map_part_2.data.dart";
import "package:flags/src/data/flags_map_part_3.data.dart";
import "package:sealed_countries/sealed_countries.dart";

import "ui/flags/striped_flag.dart";

// ignore: prefer-static-class, to follow pattern from eco-system.
const flagsMap = {
  CountryAbw(): StripedFlag(flagAbwProperties),
  CountryAfg(): StripedFlag(flagAfgProperties),
  CountryAgo(): StripedFlag(flagAgoProperties),
  CountryAia(): StripedFlag(flagAiaProperties),
  CountryAla(): StripedFlag(flagAlaProperties),
  CountryAlb(): StripedFlag(flagAlbProperties),
  CountryAnd(): StripedFlag(flagAndProperties),
  CountryAre(): StripedFlag(flagAreProperties),
  CountryArg(): StripedFlag(flagArgProperties),
  // CountryArm(): StripedFlag(flagArmProperties),
  CountryAsm(): StripedFlag(flagAsmProperties),
  CountryAta(): StripedFlag(flagAtaProperties),
  CountryAtf(): StripedFlag(flagAtfProperties),
  CountryAtg(): StripedFlag(flagAtgProperties),
  CountryAus(): StripedFlag(flagAusProperties),
  // CountryAut(): StripedFlag(flagAutProperties),
  CountryAze(): StripedFlag(flagAzeProperties),
  CountryBdi(): StripedFlag(flagBdiProperties),
  // CountryBel(): StripedFlag(flagBelProperties),
  CountryBen(): StripedFlag(flagBenProperties),
  // CountryBes(): StripedFlag(flagBesProperties),
  CountryBfa(): StripedFlag(flagBfaProperties),
  CountryBgd(): StripedFlag(flagBgdProperties),
  // CountryBgr(): StripedFlag(flagBgrProperties),
  CountryBhr(): StripedFlag(flagBhrProperties),
  CountryBhs(): StripedFlag(flagBhsProperties),
  CountryBih(): StripedFlag(flagBihProperties),
  // CountryBlm(): StripedFlag(flagBlmProperties),
  CountryBlr(): StripedFlag(flagBlrProperties),
  CountryBlz(): StripedFlag(flagBlzProperties),
  CountryBmu(): StripedFlag(flagBmuProperties),
  // CountryBol(): StripedFlag(flagBolProperties),
  CountryBra(): StripedFlag(flagBraProperties),
  CountryBrb(): StripedFlag(flagBrbProperties),
  CountryBrn(): StripedFlag(flagBrnProperties),
  CountryBtn(): StripedFlag(flagBtnProperties),
  CountryBvt(): StripedFlag(flagBvtProperties),
  // CountryBwa(): StripedFlag(flagBwaProperties),
  CountryCaf(): StripedFlag(flagCafProperties),
  CountryCan(): StripedFlag(flagCanProperties),
  CountryCck(): StripedFlag(flagCckProperties),
  CountryChe(): StripedFlag(flagCheProperties),
  CountryChl(): StripedFlag(flagChlProperties),
  CountryChn(): StripedFlag(flagChnProperties),
  // CountryCiv(): StripedFlag(flagCivProperties),
  CountryCmr(): StripedFlag(flagCmrProperties),
  CountryCod(): StripedFlag(flagCodProperties),
  CountryCog(): StripedFlag(flagCogProperties),
  CountryCok(): StripedFlag(flagCokProperties),
  // CountryCol(): StripedFlag(flagColProperties),
  CountryCom(): StripedFlag(flagComProperties),
  CountryCpv(): StripedFlag(flagCpvProperties),
  CountryCri(): StripedFlag(flagCriProperties),
  CountryCub(): StripedFlag(flagCubProperties),
  CountryCuw(): StripedFlag(flagCuwProperties),
  CountryCxr(): StripedFlag(flagCxrProperties),
  CountryCym(): StripedFlag(flagCymProperties),
  CountryCyp(): StripedFlag(flagCypProperties),
  CountryCze(): StripedFlag(flagCzeProperties),
  // CountryDeu(): StripedFlag(flagDeuProperties),
  CountryDji(): StripedFlag(flagDjiProperties),
  CountryDma(): StripedFlag(flagDmaProperties),
  CountryDnk(): StripedFlag(flagDnkProperties),
  CountryDom(): StripedFlag(flagDomProperties),
  CountryDza(): StripedFlag(flagDzaProperties),
  CountryEcu(): StripedFlag(flagEcuProperties),
  CountryEgy(): StripedFlag(flagEgyProperties),
  CountryEri(): StripedFlag(flagEriProperties),
  CountryEsh(): StripedFlag(flagEshProperties),
  CountryEsp(): StripedFlag(flagEspProperties),
  // CountryEst(): StripedFlag(flagEstProperties),
  CountryEth(): StripedFlag(flagEthProperties),
  CountryFin(): StripedFlag(flagFinProperties),
  CountryFji(): StripedFlag(flagFjiProperties),
  CountryFlk(): StripedFlag(flagFlkProperties),
  // CountryFra(): StripedFlag(flagFraProperties),
  CountryFro(): StripedFlag(flagFroProperties),
  CountryFsm(): StripedFlag(flagFsmProperties),
  // CountryGab(): StripedFlag(flagGabProperties),
  CountryGbr(): StripedFlag(flagGbrProperties),
  CountryGeo(): StripedFlag(flagGeoProperties),
  CountryGgy(): StripedFlag(flagGgyProperties),
  CountryGha(): StripedFlag(flagGhaProperties),
  CountryGib(): StripedFlag(flagGibProperties),
  // CountryGin(): StripedFlag(flagGinProperties),
  // CountryGlp(): StripedFlag(flagGlpProperties),
  // CountryGmb(): StripedFlag(flagGmbProperties),
  CountryGnb(): StripedFlag(flagGnbProperties),
  CountryGnq(): StripedFlag(flagGnqProperties),
  CountryGrc(): StripedFlag(flagGrcProperties),
  CountryGrd(): StripedFlag(flagGrdProperties),
  CountryGrl(): StripedFlag(flagGrlProperties),
  CountryGtm(): StripedFlag(flagGtmProperties),
  // CountryGuf(): StripedFlag(flagGufProperties),
  CountryGum(): StripedFlag(flagGumProperties),
  CountryGuy(): StripedFlag(flagGuyProperties),
  CountryHkg(): StripedFlag(flagHkgProperties),
  CountryHmd(): StripedFlag(flagHmdProperties),
  CountryHnd(): StripedFlag(flagHndProperties),
  CountryHrv(): StripedFlag(flagHrvProperties),
  CountryHti(): StripedFlag(flagHtiProperties),
  // CountryHun(): StripedFlag(flagHunProperties),
  // CountryIdn(): StripedFlag(flagIdnProperties),
  CountryImn(): StripedFlag(flagImnProperties),
  CountryInd(): StripedFlag(flagIndProperties),
  CountryIot(): StripedFlag(flagIotProperties),
  // CountryIrl(): StripedFlag(flagIrlProperties),
  CountryIrn(): StripedFlag(flagIrnProperties),
  CountryIrq(): StripedFlag(flagIrqProperties),
  CountryIsl(): StripedFlag(flagIslProperties),
  CountryIsr(): StripedFlag(flagIsrProperties),
  // CountryIta(): StripedFlag(flagItaProperties),
  CountryJam(): StripedFlag(flagJamProperties),
  CountryJey(): StripedFlag(flagJeyProperties),
  CountryJor(): StripedFlag(flagJorProperties),
  CountryJpn(): StripedFlag(flagJpnProperties),
  CountryKaz(): StripedFlag(flagKazProperties),
  CountryKen(): StripedFlag(flagKenProperties),
  CountryKgz(): StripedFlag(flagKgzProperties),
  CountryKhm(): StripedFlag(flagKhmProperties),
  CountryKir(): StripedFlag(flagKirProperties),
  CountryKna(): StripedFlag(flagKnaProperties),
  CountryKor(): StripedFlag(flagKorProperties),
  CountryKwt(): StripedFlag(flagKwtProperties),
  CountryLao(): StripedFlag(flagLaoProperties),
  CountryLbn(): StripedFlag(flagLbnProperties),
  CountryLbr(): StripedFlag(flagLbrProperties),
  CountryLby(): StripedFlag(flagLbyProperties),
  CountryLca(): StripedFlag(flagLcaProperties),
  CountryLie(): StripedFlag(flagLieProperties),
  CountryLka(): StripedFlag(flagLkaProperties),
  CountryLso(): StripedFlag(flagLsoProperties),
  // CountryLtu(): StripedFlag(flagLtuProperties),
  // CountryLux(): StripedFlag(flagLuxProperties),
  // CountryLva(): StripedFlag(flagLvaProperties),
  CountryMac(): StripedFlag(flagMacProperties),
  // CountryMaf(): StripedFlag(flagMafProperties),
  CountryMar(): StripedFlag(flagMarProperties),
  // CountryMco(): StripedFlag(flagMcoProperties),
  CountryMda(): StripedFlag(flagMdaProperties),
  CountryMdg(): StripedFlag(flagMdgProperties),
  CountryMdv(): StripedFlag(flagMdvProperties),
  CountryMex(): StripedFlag(flagMexProperties),
  CountryMhl(): StripedFlag(flagMhlProperties),
  CountryMkd(): StripedFlag(flagMkdProperties),
  // CountryMli(): StripedFlag(flagMliProperties),
  CountryMlt(): StripedFlag(flagMltProperties),
  CountryMmr(): StripedFlag(flagMmrProperties),
  CountryMne(): StripedFlag(flagMneProperties),
  CountryMng(): StripedFlag(flagMngProperties),
  CountryMnp(): StripedFlag(flagMnpProperties),
  CountryMoz(): StripedFlag(flagMozProperties),
  CountryMrt(): StripedFlag(flagMrtProperties),
  CountryMsr(): StripedFlag(flagMsrProperties),
  CountryMtq(): StripedFlag(flagMtqProperties),
  // CountryMus(): StripedFlag(flagMusProperties),
  CountryMwi(): StripedFlag(flagMwiProperties),
  CountryMys(): StripedFlag(flagMysProperties),
  // CountryMyt(): StripedFlag(flagMytProperties),
  CountryNam(): StripedFlag(flagNamProperties),
  // CountryNcl(): StripedFlag(flagNclProperties),
  CountryNer(): StripedFlag(flagNerProperties),
  CountryNfk(): StripedFlag(flagNfkProperties),
  // CountryNga(): StripedFlag(flagNgaProperties),
  CountryNic(): StripedFlag(flagNicProperties),
  CountryNiu(): StripedFlag(flagNiuProperties),
  // CountryNld(): StripedFlag(flagNldProperties),
  CountryNor(): StripedFlag(flagNorProperties),
  CountryNpl(): StripedFlag(flagNplProperties),
  CountryNru(): StripedFlag(flagNruProperties),
  CountryNzl(): StripedFlag(flagNzlProperties),
  CountryOmn(): StripedFlag(flagOmnProperties),
  CountryPak(): StripedFlag(flagPakProperties),
  CountryPan(): StripedFlag(flagPanProperties),
  CountryPcn(): StripedFlag(flagPcnProperties),
  // CountryPer(): StripedFlag(flagPerProperties),
  CountryPhl(): StripedFlag(flagPhlProperties),
  CountryPlw(): StripedFlag(flagPlwProperties),
  CountryPng(): StripedFlag(flagPngProperties),
  // CountryPol(): StripedFlag(flagPolProperties),
  CountryPri(): StripedFlag(flagPriProperties),
  CountryPrk(): StripedFlag(flagPrkProperties),
  CountryPrt(): StripedFlag(flagPrtProperties),
  CountryPry(): StripedFlag(flagPryProperties),
  CountryPse(): StripedFlag(flagPseProperties),
  CountryPyf(): StripedFlag(flagPyfProperties),
  CountryQat(): StripedFlag(flagQatProperties),
  // CountryReu(): StripedFlag(flagReuProperties),
  // CountryRou(): StripedFlag(flagRouProperties),
  // CountryRus(): StripedFlag(flagRusProperties),
  CountryRwa(): StripedFlag(flagRwaProperties),
  CountrySau(): StripedFlag(flagSauProperties),
  CountrySdn(): StripedFlag(flagSdnProperties),
  CountrySen(): StripedFlag(flagSenProperties),
  CountrySgp(): StripedFlag(flagSgpProperties),
  CountrySgs(): StripedFlag(flagSgsProperties),
  CountryShn(): StripedFlag(flagShnProperties),
  CountrySjm(): StripedFlag(flagSjmProperties),
  CountrySlb(): StripedFlag(flagSlbProperties),
  // CountrySle(): StripedFlag(flagSleProperties),
  CountrySlv(): StripedFlag(flagSlvProperties),
  CountrySmr(): StripedFlag(flagSmrProperties),
  CountrySom(): StripedFlag(flagSomProperties),
  // CountrySpm(): StripedFlag(flagSpmProperties),
  CountrySrb(): StripedFlag(flagSrbProperties),
  CountrySsd(): StripedFlag(flagSsdProperties),
  CountryStp(): StripedFlag(flagStpProperties),
  CountrySur(): StripedFlag(flagSurProperties),
  CountrySvk(): StripedFlag(flagSvkProperties),
  CountrySvn(): StripedFlag(flagSvnProperties),
  CountrySwe(): StripedFlag(flagSweProperties),
  CountrySwz(): StripedFlag(flagSwzProperties),
  CountrySxm(): StripedFlag(flagSxmProperties),
  CountrySyc(): StripedFlag(flagSycProperties),
  CountrySyr(): StripedFlag(flagSyrProperties),
  CountryTca(): StripedFlag(flagTcaProperties),
  // CountryTcd(): StripedFlag(flagTcdProperties),
  CountryTgo(): StripedFlag(flagTgoProperties),
  // CountryTha(): StripedFlag(flagThaProperties),
  CountryTjk(): StripedFlag(flagTjkProperties),
  CountryTkl(): StripedFlag(flagTklProperties),
  CountryTkm(): StripedFlag(flagTkmProperties),
  CountryTls(): StripedFlag(flagTlsProperties),
  CountryTon(): StripedFlag(flagTonProperties),
  CountryTto(): StripedFlag(flagTtoProperties),
  CountryTun(): StripedFlag(flagTunProperties),
  CountryTur(): StripedFlag(flagTurProperties),
  CountryTuv(): StripedFlag(flagTuvProperties),
  CountryTwn(): StripedFlag(flagTwnProperties),
  CountryTza(): StripedFlag(flagTzaProperties),
  CountryUga(): StripedFlag(flagUgaProperties),
  // CountryUkr(): StripedFlag(flagUkrProperties),
  CountryUmi(): StripedFlag(flagUmiProperties),
  CountryUry(): StripedFlag(flagUryProperties),
  CountryUsa(): StripedFlag(flagUsaProperties),
  CountryUzb(): StripedFlag(flagUzbProperties),
  CountryVat(): StripedFlag(flagVatProperties),
  CountryVct(): StripedFlag(flagVctProperties),
  CountryVen(): StripedFlag(flagVenProperties),
  CountryVgb(): StripedFlag(flagVgbProperties),
  CountryVir(): StripedFlag(flagVirProperties),
  CountryVnm(): StripedFlag(flagVnmProperties),
  CountryVut(): StripedFlag(flagVutProperties),
  // CountryWlf(): StripedFlag(flagWlfProperties),
  CountryWsm(): StripedFlag(flagWsmProperties),
  // CountryYem(): StripedFlag(flagYemProperties),
  CountryZaf(): StripedFlag(flagZafProperties),
  CountryZmb(): StripedFlag(flagZmbProperties),
  CountryZwe(): StripedFlag(flagZweProperties),
  CountryUnk(): StripedFlag(flagUnkProperties),
};
