// ignore_for_file: depend_on_referenced_packages

import "package:flags/src/data/flags_map_part_1.data.dart";
import "package:flags/src/data/flags_map_part_2.data.dart";
import "package:flags/src/data/flags_map_part_3.data.dart";
import "package:sealed_countries/sealed_countries.dart";

import "ui/flags/basic_flag.dart";
// import "ui/flags/star_flag.dart";
// import "ui/flags/rectangle_flag.dart";
// import "ui/flags/triangle_flag.dart";
// import "ui/flags/disc_flag.dart";

// ignore: prefer-static-class, to follow pattern from eco-system.
const flagsMap = {
  CountryAbw(): BasicFlag(flagAbwProperties),
  CountryAfg(): BasicFlag(flagAfgProperties),
  CountryAgo(): BasicFlag(flagAgoProperties),
  CountryAia(): BasicFlag(flagAiaProperties),
  CountryAla(): BasicFlag(flagAlaProperties),
  CountryAlb(): BasicFlag(flagAlbProperties),
  CountryAnd(): BasicFlag(flagAndProperties),
  // CountryAre(): RectangleFlag(flagAreProperties),
  CountryArg(): BasicFlag(flagArgProperties),
  // CountryArm(): BasicFlag(flagArmProperties),
  CountryAsm(): BasicFlag(flagAsmProperties),
  CountryAta(): BasicFlag(flagAtaProperties),
  CountryAtf(): BasicFlag(flagAtfProperties),
  CountryAtg(): BasicFlag(flagAtgProperties),
  CountryAus(): BasicFlag(flagAusProperties),
  // CountryAut(): BasicFlag(flagAutProperties),
  CountryAze(): BasicFlag(flagAzeProperties),
  CountryBdi(): BasicFlag(flagBdiProperties),
  // CountryBel(): BasicFlag(flagBelProperties),
  // CountryBen(): RectangleFlag(flagBenProperties),
  // CountryBes(): BasicFlag(flagBesProperties),
  // CountryBfa(): StarFlag(flagBfaProperties),
  // CountryBgd(): DiscFlag(flagBgdProperties),
  // CountryBgr(): BasicFlag(flagBgrProperties),
  CountryBhr(): BasicFlag(flagBhrProperties),
  // CountryBhs(): TriangleFlag(flagBhsProperties),
  CountryBih(): BasicFlag(flagBihProperties),
  // CountryBlm(): BasicFlag(flagBlmProperties),
  CountryBlr(): BasicFlag(flagBlrProperties),
  CountryBlz(): BasicFlag(flagBlzProperties),
  CountryBmu(): BasicFlag(flagBmuProperties),
  // CountryBol(): BasicFlag(flagBolProperties),
  CountryBra(): BasicFlag(flagBraProperties),
  CountryBrb(): BasicFlag(flagBrbProperties),
  CountryBrn(): BasicFlag(flagBrnProperties),
  CountryBtn(): BasicFlag(flagBtnProperties),
  CountryBvt(): BasicFlag(flagBvtProperties),
  // CountryBwa(): BasicFlag(flagBwaProperties),
  CountryCaf(): BasicFlag(flagCafProperties),
  CountryCan(): BasicFlag(flagCanProperties),
  CountryCck(): BasicFlag(flagCckProperties),
  CountryChe(): BasicFlag(flagCheProperties),
  CountryChl(): BasicFlag(flagChlProperties),
  CountryChn(): BasicFlag(flagChnProperties),
  // CountryCiv(): BasicFlag(flagCivProperties),
  // CountryCmr(): StarFlag(flagCmrProperties),
  CountryCod(): BasicFlag(flagCodProperties),
  CountryCog(): BasicFlag(flagCogProperties),
  CountryCok(): BasicFlag(flagCokProperties),
  // CountryCol(): BasicFlag(flagColProperties),
  CountryCom(): BasicFlag(flagComProperties),
  CountryCpv(): BasicFlag(flagCpvProperties),
  CountryCri(): BasicFlag(flagCriProperties),
  CountryCub(): BasicFlag(flagCubProperties),
  CountryCuw(): BasicFlag(flagCuwProperties),
  CountryCxr(): BasicFlag(flagCxrProperties),
  CountryCym(): BasicFlag(flagCymProperties),
  CountryCyp(): BasicFlag(flagCypProperties),
  // CountryCze(): TriangleFlag(flagCzeProperties),
  // CountryDeu(): BasicFlag(flagDeuProperties),
  CountryDji(): BasicFlag(flagDjiProperties),
  CountryDma(): BasicFlag(flagDmaProperties),
  // CountryDnk(): RectangleFlag(flagDnkProperties),
  CountryDom(): BasicFlag(flagDomProperties),
  CountryDza(): BasicFlag(flagDzaProperties),
  CountryEcu(): BasicFlag(flagEcuProperties),
  CountryEgy(): BasicFlag(flagEgyProperties),
  CountryEri(): BasicFlag(flagEriProperties),
  CountryEsh(): BasicFlag(flagEshProperties),
  CountryEsp(): BasicFlag(flagEspProperties),
  // CountryEst(): BasicFlag(flagEstProperties),
  CountryEth(): BasicFlag(flagEthProperties),
  // CountryFin(): RectangleFlag(flagFinProperties),
  CountryFji(): BasicFlag(flagFjiProperties),
  CountryFlk(): BasicFlag(flagFlkProperties),
  // CountryFra(): BasicFlag(flagFraProperties),
  CountryFro(): BasicFlag(flagFroProperties),
  CountryFsm(): BasicFlag(flagFsmProperties),
  // CountryGab(): BasicFlag(flagGabProperties),
  CountryGbr(): BasicFlag(flagGbrProperties),
  CountryGeo(): BasicFlag(flagGeoProperties),
  CountryGgy(): BasicFlag(flagGgyProperties),
  // CountryGha(): StarFlag(flagGhaProperties),
  CountryGib(): BasicFlag(flagGibProperties),
  // CountryGin(): BasicFlag(flagGinProperties),
  // CountryGlp(): BasicFlag(flagGlpProperties),
  // CountryGmb(): BasicFlag(flagGmbProperties),
  CountryGnb(): BasicFlag(flagGnbProperties),
  CountryGnq(): BasicFlag(flagGnqProperties),
  CountryGrc(): BasicFlag(flagGrcProperties),
  CountryGrd(): BasicFlag(flagGrdProperties),
  CountryGrl(): BasicFlag(flagGrlProperties),
  CountryGtm(): BasicFlag(flagGtmProperties),
  // CountryGuf(): BasicFlag(flagGufProperties),
  CountryGum(): BasicFlag(flagGumProperties),
  CountryGuy(): BasicFlag(flagGuyProperties),
  CountryHkg(): BasicFlag(flagHkgProperties),
  CountryHmd(): BasicFlag(flagHmdProperties),
  CountryHnd(): BasicFlag(flagHndProperties),
  CountryHrv(): BasicFlag(flagHrvProperties),
  CountryHti(): BasicFlag(flagHtiProperties),
  // CountryHun(): BasicFlag(flagHunProperties),
  // CountryIdn(): BasicFlag(flagIdnProperties),
  CountryImn(): BasicFlag(flagImnProperties),
  CountryInd(): BasicFlag(flagIndProperties),
  CountryIot(): BasicFlag(flagIotProperties),
  // CountryIrl(): BasicFlag(flagIrlProperties),
  CountryIrn(): BasicFlag(flagIrnProperties),
  CountryIrq(): BasicFlag(flagIrqProperties),
  CountryIsl(): BasicFlag(flagIslProperties),
  CountryIsr(): BasicFlag(flagIsrProperties),
  // CountryIta(): BasicFlag(flagItaProperties),
  CountryJam(): BasicFlag(flagJamProperties),
  CountryJey(): BasicFlag(flagJeyProperties),
  CountryJor(): BasicFlag(flagJorProperties),
  // CountryJpn(): DiscFlag(flagJpnProperties),
  CountryKaz(): BasicFlag(flagKazProperties),
  CountryKen(): BasicFlag(flagKenProperties),
  CountryKgz(): BasicFlag(flagKgzProperties),
  CountryKhm(): BasicFlag(flagKhmProperties),
  CountryKir(): BasicFlag(flagKirProperties),
  CountryKna(): BasicFlag(flagKnaProperties),
  CountryKor(): BasicFlag(flagKorProperties),
  CountryKwt(): BasicFlag(flagKwtProperties),
  // CountryLao(): DiscFlag(flagLaoProperties),
  CountryLbn(): BasicFlag(flagLbnProperties),
  CountryLbr(): BasicFlag(flagLbrProperties),
  CountryLby(): BasicFlag(flagLbyProperties),
  CountryLca(): BasicFlag(flagLcaProperties),
  CountryLie(): BasicFlag(flagLieProperties),
  CountryLka(): BasicFlag(flagLkaProperties),
  CountryLso(): BasicFlag(flagLsoProperties),
  // CountryLtu(): BasicFlag(flagLtuProperties),
  // CountryLux(): BasicFlag(flagLuxProperties),
  // CountryLva(): BasicFlag(flagLvaProperties),
  CountryMac(): BasicFlag(flagMacProperties),
  // CountryMaf(): BasicFlag(flagMafProperties),
  CountryMar(): BasicFlag(flagMarProperties),
  // CountryMco(): BasicFlag(flagMcoProperties),
  CountryMda(): BasicFlag(flagMdaProperties),
  // CountryMdg(): RectangleFlag(flagMdgProperties),
  CountryMdv(): BasicFlag(flagMdvProperties),
  CountryMex(): BasicFlag(flagMexProperties),
  CountryMhl(): BasicFlag(flagMhlProperties),
  CountryMkd(): BasicFlag(flagMkdProperties),
  // CountryMli(): BasicFlag(flagMliProperties),
  CountryMlt(): BasicFlag(flagMltProperties),
  // CountryMmr(): StarFlag(flagMmrProperties),
  CountryMne(): BasicFlag(flagMneProperties),
  CountryMng(): BasicFlag(flagMngProperties),
  CountryMnp(): BasicFlag(flagMnpProperties),
  CountryMoz(): BasicFlag(flagMozProperties),
  CountryMrt(): BasicFlag(flagMrtProperties),
  CountryMsr(): BasicFlag(flagMsrProperties),
  // CountryMtq(): TriangleFlag(flagMtqProperties),
  // CountryMus(): BasicFlag(flagMusProperties),
  CountryMwi(): BasicFlag(flagMwiProperties),
  CountryMys(): BasicFlag(flagMysProperties),
  // CountryMyt(): BasicFlag(flagMytProperties),
  CountryNam(): BasicFlag(flagNamProperties),
  // CountryNcl(): BasicFlag(flagNclProperties),
  // CountryNer(): DiscFlag(flagNerProperties),
  CountryNfk(): BasicFlag(flagNfkProperties),
  // CountryNga(): BasicFlag(flagNgaProperties),
  CountryNic(): BasicFlag(flagNicProperties),
  CountryNiu(): BasicFlag(flagNiuProperties),
  // CountryNld(): BasicFlag(flagNldProperties),
  CountryNor(): BasicFlag(flagNorProperties),
  CountryNpl(): BasicFlag(flagNplProperties),
  // CountryNru(): StarFlag(flagNruProperties),
  CountryNzl(): BasicFlag(flagNzlProperties),
  CountryOmn(): BasicFlag(flagOmnProperties),
  CountryPak(): BasicFlag(flagPakProperties),
  CountryPan(): BasicFlag(flagPanProperties),
  CountryPcn(): BasicFlag(flagPcnProperties),
  // CountryPer(): BasicFlag(flagPerProperties),
  CountryPhl(): BasicFlag(flagPhlProperties),
  // CountryPlw(): DiscFlag(flagPlwProperties),
  CountryPng(): BasicFlag(flagPngProperties),
  // CountryPol(): BasicFlag(flagPolProperties),
  CountryPri(): BasicFlag(flagPriProperties),
  CountryPrk(): BasicFlag(flagPrkProperties),
  CountryPrt(): BasicFlag(flagPrtProperties),
  CountryPry(): BasicFlag(flagPryProperties),
  // CountryPse(): TriangleFlag(flagPseProperties),
  CountryPyf(): BasicFlag(flagPyfProperties),
  CountryQat(): BasicFlag(flagQatProperties),
  // CountryReu(): BasicFlag(flagReuProperties),
  // CountryRou(): BasicFlag(flagRouProperties),
  // CountryRus(): BasicFlag(flagRusProperties),
  CountryRwa(): BasicFlag(flagRwaProperties),
  CountrySau(): BasicFlag(flagSauProperties),
  // CountrySdn(): TriangleFlag(flagSdnProperties),
  // CountrySen(): StarFlag(flagSenProperties),
  CountrySgp(): BasicFlag(flagSgpProperties),
  CountrySgs(): BasicFlag(flagSgsProperties),
  CountryShn(): BasicFlag(flagShnProperties),
  CountrySjm(): BasicFlag(flagSjmProperties),
  CountrySlb(): BasicFlag(flagSlbProperties),
  // CountrySle(): BasicFlag(flagSleProperties),
  CountrySlv(): BasicFlag(flagSlvProperties),
  CountrySmr(): BasicFlag(flagSmrProperties),
  // CountrySom(): StarFlag(flagSomProperties),
  // CountrySpm(): BasicFlag(flagSpmProperties),
  CountrySrb(): BasicFlag(flagSrbProperties),
  CountrySsd(): BasicFlag(flagSsdProperties),
  CountryStp(): BasicFlag(flagStpProperties),
  // CountrySur(): StarFlag(flagSurProperties),
  CountrySvk(): BasicFlag(flagSvkProperties),
  CountrySvn(): BasicFlag(flagSvnProperties),
  // CountrySwe(): RectangleFlag(flagSweProperties),
  CountrySwz(): BasicFlag(flagSwzProperties),
  CountrySxm(): BasicFlag(flagSxmProperties),
  CountrySyc(): BasicFlag(flagSycProperties),
  CountrySyr(): BasicFlag(flagSyrProperties),
  CountryTca(): BasicFlag(flagTcaProperties),
  // CountryTcd(): BasicFlag(flagTcdProperties),
  CountryTgo(): BasicFlag(flagTgoProperties),
  // CountryTha(): BasicFlag(flagThaProperties),
  CountryTjk(): BasicFlag(flagTjkProperties),
  CountryTkl(): BasicFlag(flagTklProperties),
  CountryTkm(): BasicFlag(flagTkmProperties),
  CountryTls(): BasicFlag(flagTlsProperties),
  CountryTon(): BasicFlag(flagTonProperties),
  CountryTto(): BasicFlag(flagTtoProperties),
  CountryTun(): BasicFlag(flagTunProperties),
  CountryTur(): BasicFlag(flagTurProperties),
  CountryTuv(): BasicFlag(flagTuvProperties),
  CountryTwn(): BasicFlag(flagTwnProperties),
  CountryTza(): BasicFlag(flagTzaProperties),
  CountryUga(): BasicFlag(flagUgaProperties),
  // CountryUkr(): BasicFlag(flagUkrProperties),
  CountryUmi(): BasicFlag(flagUmiProperties),
  CountryUry(): BasicFlag(flagUryProperties),
  CountryUsa(): BasicFlag(flagUsaProperties),
  CountryUzb(): BasicFlag(flagUzbProperties),
  CountryVat(): BasicFlag(flagVatProperties),
  CountryVct(): BasicFlag(flagVctProperties),
  CountryVen(): BasicFlag(flagVenProperties),
  CountryVgb(): BasicFlag(flagVgbProperties),
  CountryVir(): BasicFlag(flagVirProperties),
  // CountryVnm(): StarFlag(flagVnmProperties),
  CountryVut(): BasicFlag(flagVutProperties),
  // CountryWlf(): BasicFlag(flagWlfProperties),
  CountryWsm(): BasicFlag(flagWsmProperties),
  // CountryYem(): BasicFlag(flagYemProperties),
  CountryZaf(): BasicFlag(flagZafProperties),
  CountryZmb(): BasicFlag(flagZmbProperties),
  CountryZwe(): BasicFlag(flagZweProperties),
  CountryUnk(): BasicFlag(flagUnkProperties),
};
