name: deploy

on:
  push:
    branches: [main]
    paths:
      - "packages/world_countries/**/*.dart"
      - ".github/workflows/world_countries.yaml"
      - ".github/workflows/deploy_example_web.yaml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: 🚀 Deploy example website
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@v7.0.1

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2.23.0
        with:
          cache: true
          channel: "beta"

      - name: 📦 Install dependencies
        working-directory: packages/world_countries/example
        run: flutter pub upgrade

      - name: 🛠️ Build for web
        working-directory: packages/world_countries/example
        run: flutter build web --release --base-href=/sealed_world/ --wasm

      - name: 📤 Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: packages/world_countries/example/build/web

      - name: 🛫 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
