name: publish_world_flags

on:
  push:
    branches: [main]
    tags:
    - 'world_flags-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish-world-flags:
    uses: ./.github/workflows/publish_to_pub.yaml
    permissions:
      id-token: write
    with:
      package_name: world_flags
      tag: ${{ github.ref }}