name: sealed_countries

on:
  push:
    branches: [main]
    paths:
      - "packages/sealed_countries/**"
      - ".github/workflows/sealed_countries.yaml"
  pull_request:
    branches: [main]
    paths:
      - "packages/sealed_countries/**"
      - ".github/workflows/sealed_countries.yaml"

jobs:
  verify-countries-dart:
    uses: ./.github/workflows/dart_package_workflow.yaml
    with:
      package_name: sealed_countries
  publish-countries-dart:
    uses: ./.github/workflows/publish_to_pub.yaml
    with:
      package_name: sealed_countries