name: verify_sealed_countries

on:
  push:
    branches: [main]
    paths:
      - "packages/sealed_countries/**"
  pull_request:
    branches: [main]
    paths:
      - "packages/sealed_countries/**"
      - ".github/workflows/sealed_countries.yaml"

jobs:
  verify-sealed-countries:
    uses: ./.github/workflows/dart_package_workflow.yaml
    with:
      package_name: sealed_countries