name: verify_sealed_countries

on:
  push:
    branches: [main]
    paths:
      - "packages/sealed_countries/**/*.dart"
  pull_request:
    branches: [main]
    paths:
      - "packages/sealed_countries/**/*.dart"
      - ".github/workflows/sealed_countries.yaml"

jobs:
  verify-sealed-countries:
    uses: ./.github/workflows/verify_package_workflow.yaml
    with:
      package_name: sealed_countries
    secrets: inherit
