name: verify_world_flags

on:
  push:
    branches: [main]
    paths:
      - "packages/world_flags/**/*.dart"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/world_flags.yaml"
      - "packages/world_flags/**/*.dart"

jobs:
  verify-world-flags:
    uses: ./.github/workflows/verify_package_workflow.yaml
    with:
      package_name: world_flags
      is_flutter: true
    secrets: inherit
